/*
Customa

Testing SettingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package customa

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	customa "github.com/trust-in-dialog-Services-GmbH/customa-go/v3"
)

func Test_customa_SettingsAPIService(t *testing.T) {

	configuration := customa.NewConfiguration()
	apiClient := customa.NewAPIClient(configuration)

	t.Run("Test SettingsAPIService SettingsGetMarketplaceV4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var mappingShopId string
		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsGetMarketplaceV4(context.Background(), project, mappingShopId, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsGetV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsGetV3(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsGetV4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsGetV4(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsListV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SettingsAPI.SettingsListV3(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsListV4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SettingsAPI.SettingsListV4(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsSetMarketplaceV4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var mappingShopId string
		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsSetMarketplaceV4(context.Background(), project, mappingShopId, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsValidateV3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsValidateV3(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsAPIService SettingsValidateV4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SettingsAPI.SettingsValidateV4(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
