/*
Customa

E-Commerce BI & CRM Tool

API version: 3.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthLoginRequestV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLoginRequestV4{}

// AuthLoginRequestV4 Request body for JSON authentication.
type AuthLoginRequestV4 struct {
	// Username (E-Mail address) used for authentication with Customa.
	Username string `json:"Username"`
	// Password for the User.
	Password string `json:"Password"`
	AdditionalProperties map[string]interface{}
}

type _AuthLoginRequestV4 AuthLoginRequestV4

// NewAuthLoginRequestV4 instantiates a new AuthLoginRequestV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLoginRequestV4(username string, password string) *AuthLoginRequestV4 {
	this := AuthLoginRequestV4{}
	this.Username = username
	this.Password = password
	return &this
}

// NewAuthLoginRequestV4WithDefaults instantiates a new AuthLoginRequestV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginRequestV4WithDefaults() *AuthLoginRequestV4 {
	this := AuthLoginRequestV4{}
	return &this
}

// GetUsername returns the Username field value
func (o *AuthLoginRequestV4) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *AuthLoginRequestV4) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *AuthLoginRequestV4) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *AuthLoginRequestV4) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthLoginRequestV4) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthLoginRequestV4) SetPassword(v string) {
	o.Password = v
}

func (o AuthLoginRequestV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLoginRequestV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Username"] = o.Username
	toSerialize["Password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthLoginRequestV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Username",
		"Password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthLoginRequestV4 := _AuthLoginRequestV4{}

	err = json.Unmarshal(data, &varAuthLoginRequestV4)

	if err != nil {
		return err
	}

	*o = AuthLoginRequestV4(varAuthLoginRequestV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Username")
		delete(additionalProperties, "Password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthLoginRequestV4 struct {
	value *AuthLoginRequestV4
	isSet bool
}

func (v NullableAuthLoginRequestV4) Get() *AuthLoginRequestV4 {
	return v.value
}

func (v *NullableAuthLoginRequestV4) Set(val *AuthLoginRequestV4) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginRequestV4) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginRequestV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginRequestV4(val *AuthLoginRequestV4) *NullableAuthLoginRequestV4 {
	return &NullableAuthLoginRequestV4{value: val, isSet: true}
}

func (v NullableAuthLoginRequestV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginRequestV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


