/*
Customa

E-Commerce BI & CRM Tool

API version: 3.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the StrictReceiptItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrictReceiptItem{}

// StrictReceiptItem struct for StrictReceiptItem
type StrictReceiptItem struct {
	// Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
	CreationDate *time.Time `json:"CreationDate,omitempty"`
	// Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
	ModificationDate *time.Time `json:"ModificationDate,omitempty"`
	// ID of the product.
	ProductID string `json:"ProductID"`
	// Product number of the product.
	ProductNumber string `json:"ProductNumber"`
	// Quantity of the product.
	Quantity int32 `json:"Quantity"`
	SellingPrice Price `json:"SellingPrice"`
	PurchasePrice *Price `json:"PurchasePrice,omitempty"`
	// Tax class of the item. For example, in Germany, 19% VAT would be 'Normal' while 7% VAT would be 'Reduced'.
	TaxClass string `json:"TaxClass"`
	AdditionalProperties map[string]interface{}
}

type _StrictReceiptItem StrictReceiptItem

// NewStrictReceiptItem instantiates a new StrictReceiptItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrictReceiptItem(productID string, productNumber string, quantity int32, sellingPrice Price, taxClass string) *StrictReceiptItem {
	this := StrictReceiptItem{}
	this.ProductID = productID
	this.ProductNumber = productNumber
	this.Quantity = quantity
	this.SellingPrice = sellingPrice
	this.TaxClass = taxClass
	return &this
}

// NewStrictReceiptItemWithDefaults instantiates a new StrictReceiptItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrictReceiptItemWithDefaults() *StrictReceiptItem {
	this := StrictReceiptItem{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *StrictReceiptItem) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *StrictReceiptItem) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given time.Time and assigns it to the CreationDate field.
func (o *StrictReceiptItem) SetCreationDate(v time.Time) {
	o.CreationDate = &v
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise.
func (o *StrictReceiptItem) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetModificationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModificationDate) {
		return nil, false
	}
	return o.ModificationDate, true
}

// HasModificationDate returns a boolean if a field has been set.
func (o *StrictReceiptItem) HasModificationDate() bool {
	if o != nil && !IsNil(o.ModificationDate) {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given time.Time and assigns it to the ModificationDate field.
func (o *StrictReceiptItem) SetModificationDate(v time.Time) {
	o.ModificationDate = &v
}

// GetProductID returns the ProductID field value
func (o *StrictReceiptItem) GetProductID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductID
}

// GetProductIDOk returns a tuple with the ProductID field value
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetProductIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductID, true
}

// SetProductID sets field value
func (o *StrictReceiptItem) SetProductID(v string) {
	o.ProductID = v
}

// GetProductNumber returns the ProductNumber field value
func (o *StrictReceiptItem) GetProductNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductNumber
}

// GetProductNumberOk returns a tuple with the ProductNumber field value
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetProductNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductNumber, true
}

// SetProductNumber sets field value
func (o *StrictReceiptItem) SetProductNumber(v string) {
	o.ProductNumber = v
}

// GetQuantity returns the Quantity field value
func (o *StrictReceiptItem) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *StrictReceiptItem) SetQuantity(v int32) {
	o.Quantity = v
}

// GetSellingPrice returns the SellingPrice field value
func (o *StrictReceiptItem) GetSellingPrice() Price {
	if o == nil {
		var ret Price
		return ret
	}

	return o.SellingPrice
}

// GetSellingPriceOk returns a tuple with the SellingPrice field value
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetSellingPriceOk() (*Price, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SellingPrice, true
}

// SetSellingPrice sets field value
func (o *StrictReceiptItem) SetSellingPrice(v Price) {
	o.SellingPrice = v
}

// GetPurchasePrice returns the PurchasePrice field value if set, zero value otherwise.
func (o *StrictReceiptItem) GetPurchasePrice() Price {
	if o == nil || IsNil(o.PurchasePrice) {
		var ret Price
		return ret
	}
	return *o.PurchasePrice
}

// GetPurchasePriceOk returns a tuple with the PurchasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetPurchasePriceOk() (*Price, bool) {
	if o == nil || IsNil(o.PurchasePrice) {
		return nil, false
	}
	return o.PurchasePrice, true
}

// HasPurchasePrice returns a boolean if a field has been set.
func (o *StrictReceiptItem) HasPurchasePrice() bool {
	if o != nil && !IsNil(o.PurchasePrice) {
		return true
	}

	return false
}

// SetPurchasePrice gets a reference to the given Price and assigns it to the PurchasePrice field.
func (o *StrictReceiptItem) SetPurchasePrice(v Price) {
	o.PurchasePrice = &v
}

// GetTaxClass returns the TaxClass field value
func (o *StrictReceiptItem) GetTaxClass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaxClass
}

// GetTaxClassOk returns a tuple with the TaxClass field value
// and a boolean to check if the value has been set.
func (o *StrictReceiptItem) GetTaxClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaxClass, true
}

// SetTaxClass sets field value
func (o *StrictReceiptItem) SetTaxClass(v string) {
	o.TaxClass = v
}

func (o StrictReceiptItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrictReceiptItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.ModificationDate) {
		toSerialize["ModificationDate"] = o.ModificationDate
	}
	toSerialize["ProductID"] = o.ProductID
	toSerialize["ProductNumber"] = o.ProductNumber
	toSerialize["Quantity"] = o.Quantity
	toSerialize["SellingPrice"] = o.SellingPrice
	if !IsNil(o.PurchasePrice) {
		toSerialize["PurchasePrice"] = o.PurchasePrice
	}
	toSerialize["TaxClass"] = o.TaxClass

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrictReceiptItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ProductID",
		"ProductNumber",
		"Quantity",
		"SellingPrice",
		"TaxClass",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrictReceiptItem := _StrictReceiptItem{}

	err = json.Unmarshal(data, &varStrictReceiptItem)

	if err != nil {
		return err
	}

	*o = StrictReceiptItem(varStrictReceiptItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "CreationDate")
		delete(additionalProperties, "ModificationDate")
		delete(additionalProperties, "ProductID")
		delete(additionalProperties, "ProductNumber")
		delete(additionalProperties, "Quantity")
		delete(additionalProperties, "SellingPrice")
		delete(additionalProperties, "PurchasePrice")
		delete(additionalProperties, "TaxClass")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrictReceiptItem struct {
	value *StrictReceiptItem
	isSet bool
}

func (v NullableStrictReceiptItem) Get() *StrictReceiptItem {
	return v.value
}

func (v *NullableStrictReceiptItem) Set(val *StrictReceiptItem) {
	v.value = val
	v.isSet = true
}

func (v NullableStrictReceiptItem) IsSet() bool {
	return v.isSet
}

func (v *NullableStrictReceiptItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrictReceiptItem(val *StrictReceiptItem) *NullableStrictReceiptItem {
	return &NullableStrictReceiptItem{value: val, isSet: true}
}

func (v NullableStrictReceiptItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrictReceiptItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


