/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the StatsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsRequest{}

// StatsRequest Request for statistics data.
type StatsRequest struct {
	// The start timestamp of the period for which the statistics should be calculated.
	From time.Time `json:"From"`
	// The end timestamp of the period for which the statistics should be calculated. The end timestamp must be greater than the start timestamp.
	To time.Time `json:"To"`
	DateField DateField `json:"DateField"`
	ProductSetMode NullableProductSetMode `json:"ProductSetMode,omitempty"`
	// The grouping type determines how the data is grouped in the response.
	GroupBy string `json:"GroupBy"`
	// Filters to be applied to the data before grouping. The filters are combined using boolean AND. If a filter contains multiple values, these are combined using boolean OR.
	Filter []Filter `json:"Filter"`
	AdditionalProperties map[string]interface{}
}

type _StatsRequest StatsRequest

// NewStatsRequest instantiates a new StatsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsRequest(from time.Time, to time.Time, dateField DateField, groupBy string, filter []Filter) *StatsRequest {
	this := StatsRequest{}
	this.From = from
	this.To = to
	this.DateField = dateField
	this.GroupBy = groupBy
	this.Filter = filter
	return &this
}

// NewStatsRequestWithDefaults instantiates a new StatsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsRequestWithDefaults() *StatsRequest {
	this := StatsRequest{}
	return &this
}

// GetFrom returns the From field value
func (o *StatsRequest) GetFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *StatsRequest) GetFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *StatsRequest) SetFrom(v time.Time) {
	o.From = v
}

// GetTo returns the To field value
func (o *StatsRequest) GetTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *StatsRequest) GetToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *StatsRequest) SetTo(v time.Time) {
	o.To = v
}

// GetDateField returns the DateField field value
func (o *StatsRequest) GetDateField() DateField {
	if o == nil {
		var ret DateField
		return ret
	}

	return o.DateField
}

// GetDateFieldOk returns a tuple with the DateField field value
// and a boolean to check if the value has been set.
func (o *StatsRequest) GetDateFieldOk() (*DateField, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateField, true
}

// SetDateField sets field value
func (o *StatsRequest) SetDateField(v DateField) {
	o.DateField = v
}

// GetProductSetMode returns the ProductSetMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatsRequest) GetProductSetMode() ProductSetMode {
	if o == nil || IsNil(o.ProductSetMode.Get()) {
		var ret ProductSetMode
		return ret
	}
	return *o.ProductSetMode.Get()
}

// GetProductSetModeOk returns a tuple with the ProductSetMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatsRequest) GetProductSetModeOk() (*ProductSetMode, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductSetMode.Get(), o.ProductSetMode.IsSet()
}

// HasProductSetMode returns a boolean if a field has been set.
func (o *StatsRequest) HasProductSetMode() bool {
	if o != nil && o.ProductSetMode.IsSet() {
		return true
	}

	return false
}

// SetProductSetMode gets a reference to the given NullableProductSetMode and assigns it to the ProductSetMode field.
func (o *StatsRequest) SetProductSetMode(v ProductSetMode) {
	o.ProductSetMode.Set(&v)
}
// SetProductSetModeNil sets the value for ProductSetMode to be an explicit nil
func (o *StatsRequest) SetProductSetModeNil() {
	o.ProductSetMode.Set(nil)
}

// UnsetProductSetMode ensures that no value is present for ProductSetMode, not even an explicit nil
func (o *StatsRequest) UnsetProductSetMode() {
	o.ProductSetMode.Unset()
}

// GetGroupBy returns the GroupBy field value
func (o *StatsRequest) GetGroupBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value
// and a boolean to check if the value has been set.
func (o *StatsRequest) GetGroupByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupBy, true
}

// SetGroupBy sets field value
func (o *StatsRequest) SetGroupBy(v string) {
	o.GroupBy = v
}

// GetFilter returns the Filter field value
func (o *StatsRequest) GetFilter() []Filter {
	if o == nil {
		var ret []Filter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *StatsRequest) GetFilterOk() ([]Filter, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filter, true
}

// SetFilter sets field value
func (o *StatsRequest) SetFilter(v []Filter) {
	o.Filter = v
}

func (o StatsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["From"] = o.From
	toSerialize["To"] = o.To
	toSerialize["DateField"] = o.DateField
	if o.ProductSetMode.IsSet() {
		toSerialize["ProductSetMode"] = o.ProductSetMode.Get()
	}
	toSerialize["GroupBy"] = o.GroupBy
	toSerialize["Filter"] = o.Filter

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"From",
		"To",
		"DateField",
		"GroupBy",
		"Filter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsRequest := _StatsRequest{}

	err = json.Unmarshal(data, &varStatsRequest)

	if err != nil {
		return err
	}

	*o = StatsRequest(varStatsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "From")
		delete(additionalProperties, "To")
		delete(additionalProperties, "DateField")
		delete(additionalProperties, "ProductSetMode")
		delete(additionalProperties, "GroupBy")
		delete(additionalProperties, "Filter")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsRequest struct {
	value *StatsRequest
	isSet bool
}

func (v NullableStatsRequest) Get() *StatsRequest {
	return v.value
}

func (v *NullableStatsRequest) Set(val *StatsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsRequest(val *StatsRequest) *NullableStatsRequest {
	return &NullableStatsRequest{value: val, isSet: true}
}

func (v NullableStatsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


