/*
Customa

E-Commerce BI & CRM Tool

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// DateField the model 'DateField'
type DateField string

// List of DateField
const (
	PURCHASE_DATE DateField = "PurchaseDate"
	RECEIPT_DATE DateField = "ReceiptDate"
)

// All allowed values of DateField enum
var AllowedDateFieldEnumValues = []DateField{
	"PurchaseDate",
	"ReceiptDate",
}

func (v *DateField) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DateField(value)
	for _, existing := range AllowedDateFieldEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DateField", value)
}

// NewDateFieldFromValue returns a pointer to a valid DateField
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDateFieldFromValue(v string) (*DateField, error) {
	ev := DateField(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DateField: valid values are %v", v, AllowedDateFieldEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DateField) IsValid() bool {
	for _, existing := range AllowedDateFieldEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DateField value
func (v DateField) Ptr() *DateField {
	return &v
}

type NullableDateField struct {
	value *DateField
	isSet bool
}

func (v NullableDateField) Get() *DateField {
	return v.value
}

func (v *NullableDateField) Set(val *DateField) {
	v.value = val
	v.isSet = true
}

func (v NullableDateField) IsSet() bool {
	return v.isSet
}

func (v *NullableDateField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateField(val *DateField) *NullableDateField {
	return &NullableDateField{value: val, isSet: true}
}

func (v NullableDateField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

