/*
Customa

E-Commerce BI & CRM Tool

API version: 3.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the FieldDefinitions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldDefinitions{}

// FieldDefinitions struct for FieldDefinitions
type FieldDefinitions struct {
	Fields map[string]FieldDefinition `json:"Fields"`
	AdditionalProperties map[string]interface{}
}

type _FieldDefinitions FieldDefinitions

// NewFieldDefinitions instantiates a new FieldDefinitions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDefinitions(fields map[string]FieldDefinition) *FieldDefinitions {
	this := FieldDefinitions{}
	this.Fields = fields
	return &this
}

// NewFieldDefinitionsWithDefaults instantiates a new FieldDefinitions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDefinitionsWithDefaults() *FieldDefinitions {
	this := FieldDefinitions{}
	return &this
}

// GetFields returns the Fields field value
func (o *FieldDefinitions) GetFields() map[string]FieldDefinition {
	if o == nil {
		var ret map[string]FieldDefinition
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitions) GetFieldsOk() (*map[string]FieldDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *FieldDefinitions) SetFields(v map[string]FieldDefinition) {
	o.Fields = v
}

func (o FieldDefinitions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldDefinitions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Fields"] = o.Fields

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FieldDefinitions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldDefinitions := _FieldDefinitions{}

	err = json.Unmarshal(data, &varFieldDefinitions)

	if err != nil {
		return err
	}

	*o = FieldDefinitions(varFieldDefinitions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFieldDefinitions struct {
	value *FieldDefinitions
	isSet bool
}

func (v NullableFieldDefinitions) Get() *FieldDefinitions {
	return v.value
}

func (v *NullableFieldDefinitions) Set(val *FieldDefinitions) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDefinitions) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDefinitions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDefinitions(val *FieldDefinitions) *NullableFieldDefinitions {
	return &NullableFieldDefinitions{value: val, isSet: true}
}

func (v NullableFieldDefinitions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDefinitions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


