/*
Customa

E-Commerce BI & CRM Tool

API version: 3.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductSearchResponseV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSearchResponseV4{}

// ProductSearchResponseV4 struct for ProductSearchResponseV4
type ProductSearchResponseV4 struct {
	Products []ProductV4 `json:"Products,omitempty"`
	TotalCount int32 `json:"TotalCount"`
	CurrentPage int32 `json:"CurrentPage"`
	PagesCount int32 `json:"PagesCount"`
	PageSize int32 `json:"PageSize"`
	AdditionalProperties map[string]interface{}
}

type _ProductSearchResponseV4 ProductSearchResponseV4

// NewProductSearchResponseV4 instantiates a new ProductSearchResponseV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSearchResponseV4(totalCount int32, currentPage int32, pagesCount int32, pageSize int32) *ProductSearchResponseV4 {
	this := ProductSearchResponseV4{}
	this.TotalCount = totalCount
	this.CurrentPage = currentPage
	this.PagesCount = pagesCount
	this.PageSize = pageSize
	return &this
}

// NewProductSearchResponseV4WithDefaults instantiates a new ProductSearchResponseV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSearchResponseV4WithDefaults() *ProductSearchResponseV4 {
	this := ProductSearchResponseV4{}
	return &this
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *ProductSearchResponseV4) GetProducts() []ProductV4 {
	if o == nil || IsNil(o.Products) {
		var ret []ProductV4
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseV4) GetProductsOk() ([]ProductV4, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *ProductSearchResponseV4) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []ProductV4 and assigns it to the Products field.
func (o *ProductSearchResponseV4) SetProducts(v []ProductV4) {
	o.Products = v
}

// GetTotalCount returns the TotalCount field value
func (o *ProductSearchResponseV4) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseV4) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ProductSearchResponseV4) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetCurrentPage returns the CurrentPage field value
func (o *ProductSearchResponseV4) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseV4) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *ProductSearchResponseV4) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetPagesCount returns the PagesCount field value
func (o *ProductSearchResponseV4) GetPagesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PagesCount
}

// GetPagesCountOk returns a tuple with the PagesCount field value
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseV4) GetPagesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PagesCount, true
}

// SetPagesCount sets field value
func (o *ProductSearchResponseV4) SetPagesCount(v int32) {
	o.PagesCount = v
}

// GetPageSize returns the PageSize field value
func (o *ProductSearchResponseV4) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ProductSearchResponseV4) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ProductSearchResponseV4) SetPageSize(v int32) {
	o.PageSize = v
}

func (o ProductSearchResponseV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSearchResponseV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Products) {
		toSerialize["Products"] = o.Products
	}
	toSerialize["TotalCount"] = o.TotalCount
	toSerialize["CurrentPage"] = o.CurrentPage
	toSerialize["PagesCount"] = o.PagesCount
	toSerialize["PageSize"] = o.PageSize

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductSearchResponseV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotalCount",
		"CurrentPage",
		"PagesCount",
		"PageSize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductSearchResponseV4 := _ProductSearchResponseV4{}

	err = json.Unmarshal(data, &varProductSearchResponseV4)

	if err != nil {
		return err
	}

	*o = ProductSearchResponseV4(varProductSearchResponseV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Products")
		delete(additionalProperties, "TotalCount")
		delete(additionalProperties, "CurrentPage")
		delete(additionalProperties, "PagesCount")
		delete(additionalProperties, "PageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductSearchResponseV4 struct {
	value *ProductSearchResponseV4
	isSet bool
}

func (v NullableProductSearchResponseV4) Get() *ProductSearchResponseV4 {
	return v.value
}

func (v *NullableProductSearchResponseV4) Set(val *ProductSearchResponseV4) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSearchResponseV4) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSearchResponseV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSearchResponseV4(val *ProductSearchResponseV4) *NullableProductSearchResponseV4 {
	return &NullableProductSearchResponseV4{value: val, isSet: true}
}

func (v NullableProductSearchResponseV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSearchResponseV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


