/*
Customa

E-Commerce BI & CRM Tool

API version: 3.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CustomerV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerV4{}

// CustomerV4 struct for CustomerV4
type CustomerV4 struct {
	// ID of the customer. Set internally by Customa, any given value is ignored.
	ID NullableString `json:"ID,omitempty"`
	// Customer number from e.g. an external Shop or ERP System.
	Number string `json:"Number"`
	// Group name of the customer
	Group NullableString `json:"Group,omitempty"`
	Salutation Salutation `json:"Salutation"`
	// (Academical) title of the customer.
	Title string `json:"Title"`
	// First name of the customer.
	FirstName string `json:"FirstName"`
	// Last name of the customer.
	LastName string `json:"LastName"`
	// Company of the customer's address
	Company string `json:"Company"`
	// (Street) address of the customer
	Address string `json:"Address"`
	// Postal code of the customer's address
	PostalCode string `json:"PostalCode"`
	// Suburb of the customer's address
	Suburb string `json:"Suburb"`
	// City of the customer's address
	City string `json:"City"`
	// ISO3166-1 Alpha-2 Code of the customer's country
	Country string `json:"Country"`
	// Email address of the customer.
	EMail string `json:"EMail"`
	// Phone number of the customer.
	Phone string `json:"Phone"`
	// Date of birth of the customer.
	Birthday NullableTime `json:"Birthday,omitempty"`
	// Referrer (last cookie) of the customer.
	Referrer string `json:"Referrer"`
	// Referrer Channel of the customer.
	ReferrerChannel string `json:"ReferrerChannel"`
	// Registration date of the customer.
	RegisterDate time.Time `json:"RegisterDate"`
	// Purchase date of the customer.
	PurchaseDate NullableTime `json:"PurchaseDate,omitempty"`
	// Additional data for the customer.
	AdditionalFields map[string]string `json:"AdditionalFields"`
	// Determines if the customer is a reference customer.
	ReferenceCustomer bool `json:"ReferenceCustomer"`
	// Determines if the customer has an active contact ban.
	ContactBan bool `json:"ContactBan"`
	// Deprecated, use ExternalID instead.
	// Deprecated
	ExternalCustomerID NullableInt32 `json:"ExternalCustomerID,omitempty"`
	// ID/Number of the customer in the source system (e.g. an ERP System)
	ExternalID NullableString `json:"ExternalID,omitempty"`
	// Deprecated, use ExternalSourceCustomerID instead.
	// Deprecated
	ExternalCustomerExternalID NullableString `json:"ExternalCustomerExternalID,omitempty"`
	// ID/Number of the customer in a secondary source system (e.g. the shop)
	ExternalSourceCustomerID NullableString `json:"ExternalSourceCustomerID,omitempty"`
	// Deprecated, use ExternalType instead.
	// Deprecated
	ExternalOrderType NullableString `json:"ExternalOrderType,omitempty"`
	// External type of the customer.
	ExternalType NullableString `json:"ExternalType,omitempty"`
	// Deprecated, use ExternalAccountID instead.
	// Deprecated
	ExternalOrderAccountID NullableInt32 `json:"ExternalOrderAccountID,omitempty"`
	// External account ID of the customer.
	ExternalAccountID NullableString `json:"ExternalAccountID,omitempty"`
	// Deprecated, use ExternalSourceID instead.
	// Deprecated
	ExternalOrderSubAccountID NullableString `json:"ExternalOrderSubAccountID,omitempty"`
	// External source ID of the customer.
	ExternalSourceID NullableString `json:"ExternalSourceID,omitempty"`
	// Marketplace of the customer.
	Marketplace string `json:"Marketplace"`
	TestUser bool `json:"TestUser"`
	Newsletter bool `json:"Newsletter"`
	// Segment of the customer. Read-only, changes via the API will have no effect.
	Segment string `json:"Segment"`
	// Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
	CreationDate NullableTime `json:"CreationDate,omitempty"`
	// Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
	ModificationDate NullableTime `json:"ModificationDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerV4 CustomerV4

// NewCustomerV4 instantiates a new CustomerV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerV4(number string, salutation Salutation, title string, firstName string, lastName string, company string, address string, postalCode string, suburb string, city string, country string, eMail string, phone string, referrer string, referrerChannel string, registerDate time.Time, additionalFields map[string]string, referenceCustomer bool, contactBan bool, marketplace string, testUser bool, newsletter bool, segment string) *CustomerV4 {
	this := CustomerV4{}
	this.Number = number
	this.Salutation = salutation
	this.Title = title
	this.FirstName = firstName
	this.LastName = lastName
	this.Company = company
	this.Address = address
	this.PostalCode = postalCode
	this.Suburb = suburb
	this.City = city
	this.Country = country
	this.EMail = eMail
	this.Phone = phone
	this.Referrer = referrer
	this.ReferrerChannel = referrerChannel
	this.RegisterDate = registerDate
	this.AdditionalFields = additionalFields
	this.ReferenceCustomer = referenceCustomer
	this.ContactBan = contactBan
	this.Marketplace = marketplace
	this.TestUser = testUser
	this.Newsletter = newsletter
	this.Segment = segment
	return &this
}

// NewCustomerV4WithDefaults instantiates a new CustomerV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerV4WithDefaults() *CustomerV4 {
	this := CustomerV4{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetID() string {
	if o == nil || IsNil(o.ID.Get()) {
		var ret string
		return ret
	}
	return *o.ID.Get()
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ID.Get(), o.ID.IsSet()
}

// HasID returns a boolean if a field has been set.
func (o *CustomerV4) HasID() bool {
	if o != nil && o.ID.IsSet() {
		return true
	}

	return false
}

// SetID gets a reference to the given NullableString and assigns it to the ID field.
func (o *CustomerV4) SetID(v string) {
	o.ID.Set(&v)
}
// SetIDNil sets the value for ID to be an explicit nil
func (o *CustomerV4) SetIDNil() {
	o.ID.Set(nil)
}

// UnsetID ensures that no value is present for ID, not even an explicit nil
func (o *CustomerV4) UnsetID() {
	o.ID.Unset()
}

// GetNumber returns the Number field value
func (o *CustomerV4) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *CustomerV4) SetNumber(v string) {
	o.Number = v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetGroup() string {
	if o == nil || IsNil(o.Group.Get()) {
		var ret string
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *CustomerV4) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableString and assigns it to the Group field.
func (o *CustomerV4) SetGroup(v string) {
	o.Group.Set(&v)
}
// SetGroupNil sets the value for Group to be an explicit nil
func (o *CustomerV4) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *CustomerV4) UnsetGroup() {
	o.Group.Unset()
}

// GetSalutation returns the Salutation field value
func (o *CustomerV4) GetSalutation() Salutation {
	if o == nil {
		var ret Salutation
		return ret
	}

	return o.Salutation
}

// GetSalutationOk returns a tuple with the Salutation field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetSalutationOk() (*Salutation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Salutation, true
}

// SetSalutation sets field value
func (o *CustomerV4) SetSalutation(v Salutation) {
	o.Salutation = v
}

// GetTitle returns the Title field value
func (o *CustomerV4) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CustomerV4) SetTitle(v string) {
	o.Title = v
}

// GetFirstName returns the FirstName field value
func (o *CustomerV4) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *CustomerV4) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *CustomerV4) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *CustomerV4) SetLastName(v string) {
	o.LastName = v
}

// GetCompany returns the Company field value
func (o *CustomerV4) GetCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *CustomerV4) SetCompany(v string) {
	o.Company = v
}

// GetAddress returns the Address field value
func (o *CustomerV4) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *CustomerV4) SetAddress(v string) {
	o.Address = v
}

// GetPostalCode returns the PostalCode field value
func (o *CustomerV4) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *CustomerV4) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetSuburb returns the Suburb field value
func (o *CustomerV4) GetSuburb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Suburb
}

// GetSuburbOk returns a tuple with the Suburb field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetSuburbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Suburb, true
}

// SetSuburb sets field value
func (o *CustomerV4) SetSuburb(v string) {
	o.Suburb = v
}

// GetCity returns the City field value
func (o *CustomerV4) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *CustomerV4) SetCity(v string) {
	o.City = v
}

// GetCountry returns the Country field value
func (o *CustomerV4) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *CustomerV4) SetCountry(v string) {
	o.Country = v
}

// GetEMail returns the EMail field value
func (o *CustomerV4) GetEMail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EMail
}

// GetEMailOk returns a tuple with the EMail field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetEMailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EMail, true
}

// SetEMail sets field value
func (o *CustomerV4) SetEMail(v string) {
	o.EMail = v
}

// GetPhone returns the Phone field value
func (o *CustomerV4) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *CustomerV4) SetPhone(v string) {
	o.Phone = v
}

// GetBirthday returns the Birthday field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetBirthday() time.Time {
	if o == nil || IsNil(o.Birthday.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Birthday.Get()
}

// GetBirthdayOk returns a tuple with the Birthday field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetBirthdayOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Birthday.Get(), o.Birthday.IsSet()
}

// HasBirthday returns a boolean if a field has been set.
func (o *CustomerV4) HasBirthday() bool {
	if o != nil && o.Birthday.IsSet() {
		return true
	}

	return false
}

// SetBirthday gets a reference to the given NullableTime and assigns it to the Birthday field.
func (o *CustomerV4) SetBirthday(v time.Time) {
	o.Birthday.Set(&v)
}
// SetBirthdayNil sets the value for Birthday to be an explicit nil
func (o *CustomerV4) SetBirthdayNil() {
	o.Birthday.Set(nil)
}

// UnsetBirthday ensures that no value is present for Birthday, not even an explicit nil
func (o *CustomerV4) UnsetBirthday() {
	o.Birthday.Unset()
}

// GetReferrer returns the Referrer field value
func (o *CustomerV4) GetReferrer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Referrer
}

// GetReferrerOk returns a tuple with the Referrer field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetReferrerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Referrer, true
}

// SetReferrer sets field value
func (o *CustomerV4) SetReferrer(v string) {
	o.Referrer = v
}

// GetReferrerChannel returns the ReferrerChannel field value
func (o *CustomerV4) GetReferrerChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferrerChannel
}

// GetReferrerChannelOk returns a tuple with the ReferrerChannel field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetReferrerChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferrerChannel, true
}

// SetReferrerChannel sets field value
func (o *CustomerV4) SetReferrerChannel(v string) {
	o.ReferrerChannel = v
}

// GetRegisterDate returns the RegisterDate field value
func (o *CustomerV4) GetRegisterDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RegisterDate
}

// GetRegisterDateOk returns a tuple with the RegisterDate field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetRegisterDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegisterDate, true
}

// SetRegisterDate sets field value
func (o *CustomerV4) SetRegisterDate(v time.Time) {
	o.RegisterDate = v
}

// GetPurchaseDate returns the PurchaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetPurchaseDate() time.Time {
	if o == nil || IsNil(o.PurchaseDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PurchaseDate.Get()
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetPurchaseDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchaseDate.Get(), o.PurchaseDate.IsSet()
}

// HasPurchaseDate returns a boolean if a field has been set.
func (o *CustomerV4) HasPurchaseDate() bool {
	if o != nil && o.PurchaseDate.IsSet() {
		return true
	}

	return false
}

// SetPurchaseDate gets a reference to the given NullableTime and assigns it to the PurchaseDate field.
func (o *CustomerV4) SetPurchaseDate(v time.Time) {
	o.PurchaseDate.Set(&v)
}
// SetPurchaseDateNil sets the value for PurchaseDate to be an explicit nil
func (o *CustomerV4) SetPurchaseDateNil() {
	o.PurchaseDate.Set(nil)
}

// UnsetPurchaseDate ensures that no value is present for PurchaseDate, not even an explicit nil
func (o *CustomerV4) UnsetPurchaseDate() {
	o.PurchaseDate.Unset()
}

// GetAdditionalFields returns the AdditionalFields field value
func (o *CustomerV4) GetAdditionalFields() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetAdditionalFieldsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdditionalFields, true
}

// SetAdditionalFields sets field value
func (o *CustomerV4) SetAdditionalFields(v map[string]string) {
	o.AdditionalFields = v
}

// GetReferenceCustomer returns the ReferenceCustomer field value
func (o *CustomerV4) GetReferenceCustomer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReferenceCustomer
}

// GetReferenceCustomerOk returns a tuple with the ReferenceCustomer field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetReferenceCustomerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceCustomer, true
}

// SetReferenceCustomer sets field value
func (o *CustomerV4) SetReferenceCustomer(v bool) {
	o.ReferenceCustomer = v
}

// GetContactBan returns the ContactBan field value
func (o *CustomerV4) GetContactBan() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ContactBan
}

// GetContactBanOk returns a tuple with the ContactBan field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetContactBanOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactBan, true
}

// SetContactBan sets field value
func (o *CustomerV4) SetContactBan(v bool) {
	o.ContactBan = v
}

// GetExternalCustomerID returns the ExternalCustomerID field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *CustomerV4) GetExternalCustomerID() int32 {
	if o == nil || IsNil(o.ExternalCustomerID.Get()) {
		var ret int32
		return ret
	}
	return *o.ExternalCustomerID.Get()
}

// GetExternalCustomerIDOk returns a tuple with the ExternalCustomerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *CustomerV4) GetExternalCustomerIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalCustomerID.Get(), o.ExternalCustomerID.IsSet()
}

// HasExternalCustomerID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalCustomerID() bool {
	if o != nil && o.ExternalCustomerID.IsSet() {
		return true
	}

	return false
}

// SetExternalCustomerID gets a reference to the given NullableInt32 and assigns it to the ExternalCustomerID field.
// Deprecated
func (o *CustomerV4) SetExternalCustomerID(v int32) {
	o.ExternalCustomerID.Set(&v)
}
// SetExternalCustomerIDNil sets the value for ExternalCustomerID to be an explicit nil
func (o *CustomerV4) SetExternalCustomerIDNil() {
	o.ExternalCustomerID.Set(nil)
}

// UnsetExternalCustomerID ensures that no value is present for ExternalCustomerID, not even an explicit nil
func (o *CustomerV4) UnsetExternalCustomerID() {
	o.ExternalCustomerID.Unset()
}

// GetExternalID returns the ExternalID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetExternalID() string {
	if o == nil || IsNil(o.ExternalID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalID.Get()
}

// GetExternalIDOk returns a tuple with the ExternalID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetExternalIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalID.Get(), o.ExternalID.IsSet()
}

// HasExternalID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalID() bool {
	if o != nil && o.ExternalID.IsSet() {
		return true
	}

	return false
}

// SetExternalID gets a reference to the given NullableString and assigns it to the ExternalID field.
func (o *CustomerV4) SetExternalID(v string) {
	o.ExternalID.Set(&v)
}
// SetExternalIDNil sets the value for ExternalID to be an explicit nil
func (o *CustomerV4) SetExternalIDNil() {
	o.ExternalID.Set(nil)
}

// UnsetExternalID ensures that no value is present for ExternalID, not even an explicit nil
func (o *CustomerV4) UnsetExternalID() {
	o.ExternalID.Unset()
}

// GetExternalCustomerExternalID returns the ExternalCustomerExternalID field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *CustomerV4) GetExternalCustomerExternalID() string {
	if o == nil || IsNil(o.ExternalCustomerExternalID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalCustomerExternalID.Get()
}

// GetExternalCustomerExternalIDOk returns a tuple with the ExternalCustomerExternalID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *CustomerV4) GetExternalCustomerExternalIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalCustomerExternalID.Get(), o.ExternalCustomerExternalID.IsSet()
}

// HasExternalCustomerExternalID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalCustomerExternalID() bool {
	if o != nil && o.ExternalCustomerExternalID.IsSet() {
		return true
	}

	return false
}

// SetExternalCustomerExternalID gets a reference to the given NullableString and assigns it to the ExternalCustomerExternalID field.
// Deprecated
func (o *CustomerV4) SetExternalCustomerExternalID(v string) {
	o.ExternalCustomerExternalID.Set(&v)
}
// SetExternalCustomerExternalIDNil sets the value for ExternalCustomerExternalID to be an explicit nil
func (o *CustomerV4) SetExternalCustomerExternalIDNil() {
	o.ExternalCustomerExternalID.Set(nil)
}

// UnsetExternalCustomerExternalID ensures that no value is present for ExternalCustomerExternalID, not even an explicit nil
func (o *CustomerV4) UnsetExternalCustomerExternalID() {
	o.ExternalCustomerExternalID.Unset()
}

// GetExternalSourceCustomerID returns the ExternalSourceCustomerID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetExternalSourceCustomerID() string {
	if o == nil || IsNil(o.ExternalSourceCustomerID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalSourceCustomerID.Get()
}

// GetExternalSourceCustomerIDOk returns a tuple with the ExternalSourceCustomerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetExternalSourceCustomerIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalSourceCustomerID.Get(), o.ExternalSourceCustomerID.IsSet()
}

// HasExternalSourceCustomerID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalSourceCustomerID() bool {
	if o != nil && o.ExternalSourceCustomerID.IsSet() {
		return true
	}

	return false
}

// SetExternalSourceCustomerID gets a reference to the given NullableString and assigns it to the ExternalSourceCustomerID field.
func (o *CustomerV4) SetExternalSourceCustomerID(v string) {
	o.ExternalSourceCustomerID.Set(&v)
}
// SetExternalSourceCustomerIDNil sets the value for ExternalSourceCustomerID to be an explicit nil
func (o *CustomerV4) SetExternalSourceCustomerIDNil() {
	o.ExternalSourceCustomerID.Set(nil)
}

// UnsetExternalSourceCustomerID ensures that no value is present for ExternalSourceCustomerID, not even an explicit nil
func (o *CustomerV4) UnsetExternalSourceCustomerID() {
	o.ExternalSourceCustomerID.Unset()
}

// GetExternalOrderType returns the ExternalOrderType field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *CustomerV4) GetExternalOrderType() string {
	if o == nil || IsNil(o.ExternalOrderType.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalOrderType.Get()
}

// GetExternalOrderTypeOk returns a tuple with the ExternalOrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *CustomerV4) GetExternalOrderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderType.Get(), o.ExternalOrderType.IsSet()
}

// HasExternalOrderType returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalOrderType() bool {
	if o != nil && o.ExternalOrderType.IsSet() {
		return true
	}

	return false
}

// SetExternalOrderType gets a reference to the given NullableString and assigns it to the ExternalOrderType field.
// Deprecated
func (o *CustomerV4) SetExternalOrderType(v string) {
	o.ExternalOrderType.Set(&v)
}
// SetExternalOrderTypeNil sets the value for ExternalOrderType to be an explicit nil
func (o *CustomerV4) SetExternalOrderTypeNil() {
	o.ExternalOrderType.Set(nil)
}

// UnsetExternalOrderType ensures that no value is present for ExternalOrderType, not even an explicit nil
func (o *CustomerV4) UnsetExternalOrderType() {
	o.ExternalOrderType.Unset()
}

// GetExternalType returns the ExternalType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetExternalType() string {
	if o == nil || IsNil(o.ExternalType.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalType.Get()
}

// GetExternalTypeOk returns a tuple with the ExternalType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetExternalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalType.Get(), o.ExternalType.IsSet()
}

// HasExternalType returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalType() bool {
	if o != nil && o.ExternalType.IsSet() {
		return true
	}

	return false
}

// SetExternalType gets a reference to the given NullableString and assigns it to the ExternalType field.
func (o *CustomerV4) SetExternalType(v string) {
	o.ExternalType.Set(&v)
}
// SetExternalTypeNil sets the value for ExternalType to be an explicit nil
func (o *CustomerV4) SetExternalTypeNil() {
	o.ExternalType.Set(nil)
}

// UnsetExternalType ensures that no value is present for ExternalType, not even an explicit nil
func (o *CustomerV4) UnsetExternalType() {
	o.ExternalType.Unset()
}

// GetExternalOrderAccountID returns the ExternalOrderAccountID field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *CustomerV4) GetExternalOrderAccountID() int32 {
	if o == nil || IsNil(o.ExternalOrderAccountID.Get()) {
		var ret int32
		return ret
	}
	return *o.ExternalOrderAccountID.Get()
}

// GetExternalOrderAccountIDOk returns a tuple with the ExternalOrderAccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *CustomerV4) GetExternalOrderAccountIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderAccountID.Get(), o.ExternalOrderAccountID.IsSet()
}

// HasExternalOrderAccountID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalOrderAccountID() bool {
	if o != nil && o.ExternalOrderAccountID.IsSet() {
		return true
	}

	return false
}

// SetExternalOrderAccountID gets a reference to the given NullableInt32 and assigns it to the ExternalOrderAccountID field.
// Deprecated
func (o *CustomerV4) SetExternalOrderAccountID(v int32) {
	o.ExternalOrderAccountID.Set(&v)
}
// SetExternalOrderAccountIDNil sets the value for ExternalOrderAccountID to be an explicit nil
func (o *CustomerV4) SetExternalOrderAccountIDNil() {
	o.ExternalOrderAccountID.Set(nil)
}

// UnsetExternalOrderAccountID ensures that no value is present for ExternalOrderAccountID, not even an explicit nil
func (o *CustomerV4) UnsetExternalOrderAccountID() {
	o.ExternalOrderAccountID.Unset()
}

// GetExternalAccountID returns the ExternalAccountID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetExternalAccountID() string {
	if o == nil || IsNil(o.ExternalAccountID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalAccountID.Get()
}

// GetExternalAccountIDOk returns a tuple with the ExternalAccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetExternalAccountIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalAccountID.Get(), o.ExternalAccountID.IsSet()
}

// HasExternalAccountID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalAccountID() bool {
	if o != nil && o.ExternalAccountID.IsSet() {
		return true
	}

	return false
}

// SetExternalAccountID gets a reference to the given NullableString and assigns it to the ExternalAccountID field.
func (o *CustomerV4) SetExternalAccountID(v string) {
	o.ExternalAccountID.Set(&v)
}
// SetExternalAccountIDNil sets the value for ExternalAccountID to be an explicit nil
func (o *CustomerV4) SetExternalAccountIDNil() {
	o.ExternalAccountID.Set(nil)
}

// UnsetExternalAccountID ensures that no value is present for ExternalAccountID, not even an explicit nil
func (o *CustomerV4) UnsetExternalAccountID() {
	o.ExternalAccountID.Unset()
}

// GetExternalOrderSubAccountID returns the ExternalOrderSubAccountID field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *CustomerV4) GetExternalOrderSubAccountID() string {
	if o == nil || IsNil(o.ExternalOrderSubAccountID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalOrderSubAccountID.Get()
}

// GetExternalOrderSubAccountIDOk returns a tuple with the ExternalOrderSubAccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *CustomerV4) GetExternalOrderSubAccountIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderSubAccountID.Get(), o.ExternalOrderSubAccountID.IsSet()
}

// HasExternalOrderSubAccountID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalOrderSubAccountID() bool {
	if o != nil && o.ExternalOrderSubAccountID.IsSet() {
		return true
	}

	return false
}

// SetExternalOrderSubAccountID gets a reference to the given NullableString and assigns it to the ExternalOrderSubAccountID field.
// Deprecated
func (o *CustomerV4) SetExternalOrderSubAccountID(v string) {
	o.ExternalOrderSubAccountID.Set(&v)
}
// SetExternalOrderSubAccountIDNil sets the value for ExternalOrderSubAccountID to be an explicit nil
func (o *CustomerV4) SetExternalOrderSubAccountIDNil() {
	o.ExternalOrderSubAccountID.Set(nil)
}

// UnsetExternalOrderSubAccountID ensures that no value is present for ExternalOrderSubAccountID, not even an explicit nil
func (o *CustomerV4) UnsetExternalOrderSubAccountID() {
	o.ExternalOrderSubAccountID.Unset()
}

// GetExternalSourceID returns the ExternalSourceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetExternalSourceID() string {
	if o == nil || IsNil(o.ExternalSourceID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalSourceID.Get()
}

// GetExternalSourceIDOk returns a tuple with the ExternalSourceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetExternalSourceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalSourceID.Get(), o.ExternalSourceID.IsSet()
}

// HasExternalSourceID returns a boolean if a field has been set.
func (o *CustomerV4) HasExternalSourceID() bool {
	if o != nil && o.ExternalSourceID.IsSet() {
		return true
	}

	return false
}

// SetExternalSourceID gets a reference to the given NullableString and assigns it to the ExternalSourceID field.
func (o *CustomerV4) SetExternalSourceID(v string) {
	o.ExternalSourceID.Set(&v)
}
// SetExternalSourceIDNil sets the value for ExternalSourceID to be an explicit nil
func (o *CustomerV4) SetExternalSourceIDNil() {
	o.ExternalSourceID.Set(nil)
}

// UnsetExternalSourceID ensures that no value is present for ExternalSourceID, not even an explicit nil
func (o *CustomerV4) UnsetExternalSourceID() {
	o.ExternalSourceID.Unset()
}

// GetMarketplace returns the Marketplace field value
func (o *CustomerV4) GetMarketplace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Marketplace
}

// GetMarketplaceOk returns a tuple with the Marketplace field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetMarketplaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Marketplace, true
}

// SetMarketplace sets field value
func (o *CustomerV4) SetMarketplace(v string) {
	o.Marketplace = v
}

// GetTestUser returns the TestUser field value
func (o *CustomerV4) GetTestUser() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TestUser
}

// GetTestUserOk returns a tuple with the TestUser field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetTestUserOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestUser, true
}

// SetTestUser sets field value
func (o *CustomerV4) SetTestUser(v bool) {
	o.TestUser = v
}

// GetNewsletter returns the Newsletter field value
func (o *CustomerV4) GetNewsletter() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Newsletter
}

// GetNewsletterOk returns a tuple with the Newsletter field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetNewsletterOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Newsletter, true
}

// SetNewsletter sets field value
func (o *CustomerV4) SetNewsletter(v bool) {
	o.Newsletter = v
}

// GetSegment returns the Segment field value
func (o *CustomerV4) GetSegment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Segment
}

// GetSegmentOk returns a tuple with the Segment field value
// and a boolean to check if the value has been set.
func (o *CustomerV4) GetSegmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Segment, true
}

// SetSegment sets field value
func (o *CustomerV4) SetSegment(v string) {
	o.Segment = v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate.Get()
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetCreationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreationDate.Get(), o.CreationDate.IsSet()
}

// HasCreationDate returns a boolean if a field has been set.
func (o *CustomerV4) HasCreationDate() bool {
	if o != nil && o.CreationDate.IsSet() {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given NullableTime and assigns it to the CreationDate field.
func (o *CustomerV4) SetCreationDate(v time.Time) {
	o.CreationDate.Set(&v)
}
// SetCreationDateNil sets the value for CreationDate to be an explicit nil
func (o *CustomerV4) SetCreationDateNil() {
	o.CreationDate.Set(nil)
}

// UnsetCreationDate ensures that no value is present for CreationDate, not even an explicit nil
func (o *CustomerV4) UnsetCreationDate() {
	o.CreationDate.Unset()
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerV4) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate.Get()
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerV4) GetModificationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModificationDate.Get(), o.ModificationDate.IsSet()
}

// HasModificationDate returns a boolean if a field has been set.
func (o *CustomerV4) HasModificationDate() bool {
	if o != nil && o.ModificationDate.IsSet() {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given NullableTime and assigns it to the ModificationDate field.
func (o *CustomerV4) SetModificationDate(v time.Time) {
	o.ModificationDate.Set(&v)
}
// SetModificationDateNil sets the value for ModificationDate to be an explicit nil
func (o *CustomerV4) SetModificationDateNil() {
	o.ModificationDate.Set(nil)
}

// UnsetModificationDate ensures that no value is present for ModificationDate, not even an explicit nil
func (o *CustomerV4) UnsetModificationDate() {
	o.ModificationDate.Unset()
}

func (o CustomerV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ID.IsSet() {
		toSerialize["ID"] = o.ID.Get()
	}
	toSerialize["Number"] = o.Number
	if o.Group.IsSet() {
		toSerialize["Group"] = o.Group.Get()
	}
	toSerialize["Salutation"] = o.Salutation
	toSerialize["Title"] = o.Title
	toSerialize["FirstName"] = o.FirstName
	toSerialize["LastName"] = o.LastName
	toSerialize["Company"] = o.Company
	toSerialize["Address"] = o.Address
	toSerialize["PostalCode"] = o.PostalCode
	toSerialize["Suburb"] = o.Suburb
	toSerialize["City"] = o.City
	toSerialize["Country"] = o.Country
	toSerialize["EMail"] = o.EMail
	toSerialize["Phone"] = o.Phone
	if o.Birthday.IsSet() {
		toSerialize["Birthday"] = o.Birthday.Get()
	}
	toSerialize["Referrer"] = o.Referrer
	toSerialize["ReferrerChannel"] = o.ReferrerChannel
	toSerialize["RegisterDate"] = o.RegisterDate
	if o.PurchaseDate.IsSet() {
		toSerialize["PurchaseDate"] = o.PurchaseDate.Get()
	}
	toSerialize["AdditionalFields"] = o.AdditionalFields
	toSerialize["ReferenceCustomer"] = o.ReferenceCustomer
	toSerialize["ContactBan"] = o.ContactBan
	if o.ExternalCustomerID.IsSet() {
		toSerialize["ExternalCustomerID"] = o.ExternalCustomerID.Get()
	}
	if o.ExternalID.IsSet() {
		toSerialize["ExternalID"] = o.ExternalID.Get()
	}
	if o.ExternalCustomerExternalID.IsSet() {
		toSerialize["ExternalCustomerExternalID"] = o.ExternalCustomerExternalID.Get()
	}
	if o.ExternalSourceCustomerID.IsSet() {
		toSerialize["ExternalSourceCustomerID"] = o.ExternalSourceCustomerID.Get()
	}
	if o.ExternalOrderType.IsSet() {
		toSerialize["ExternalOrderType"] = o.ExternalOrderType.Get()
	}
	if o.ExternalType.IsSet() {
		toSerialize["ExternalType"] = o.ExternalType.Get()
	}
	if o.ExternalOrderAccountID.IsSet() {
		toSerialize["ExternalOrderAccountID"] = o.ExternalOrderAccountID.Get()
	}
	if o.ExternalAccountID.IsSet() {
		toSerialize["ExternalAccountID"] = o.ExternalAccountID.Get()
	}
	if o.ExternalOrderSubAccountID.IsSet() {
		toSerialize["ExternalOrderSubAccountID"] = o.ExternalOrderSubAccountID.Get()
	}
	if o.ExternalSourceID.IsSet() {
		toSerialize["ExternalSourceID"] = o.ExternalSourceID.Get()
	}
	toSerialize["Marketplace"] = o.Marketplace
	toSerialize["TestUser"] = o.TestUser
	toSerialize["Newsletter"] = o.Newsletter
	toSerialize["Segment"] = o.Segment
	if o.CreationDate.IsSet() {
		toSerialize["CreationDate"] = o.CreationDate.Get()
	}
	if o.ModificationDate.IsSet() {
		toSerialize["ModificationDate"] = o.ModificationDate.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Number",
		"Salutation",
		"Title",
		"FirstName",
		"LastName",
		"Company",
		"Address",
		"PostalCode",
		"Suburb",
		"City",
		"Country",
		"EMail",
		"Phone",
		"Referrer",
		"ReferrerChannel",
		"RegisterDate",
		"AdditionalFields",
		"ReferenceCustomer",
		"ContactBan",
		"Marketplace",
		"TestUser",
		"Newsletter",
		"Segment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerV4 := _CustomerV4{}

	err = json.Unmarshal(data, &varCustomerV4)

	if err != nil {
		return err
	}

	*o = CustomerV4(varCustomerV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ID")
		delete(additionalProperties, "Number")
		delete(additionalProperties, "Group")
		delete(additionalProperties, "Salutation")
		delete(additionalProperties, "Title")
		delete(additionalProperties, "FirstName")
		delete(additionalProperties, "LastName")
		delete(additionalProperties, "Company")
		delete(additionalProperties, "Address")
		delete(additionalProperties, "PostalCode")
		delete(additionalProperties, "Suburb")
		delete(additionalProperties, "City")
		delete(additionalProperties, "Country")
		delete(additionalProperties, "EMail")
		delete(additionalProperties, "Phone")
		delete(additionalProperties, "Birthday")
		delete(additionalProperties, "Referrer")
		delete(additionalProperties, "ReferrerChannel")
		delete(additionalProperties, "RegisterDate")
		delete(additionalProperties, "PurchaseDate")
		delete(additionalProperties, "AdditionalFields")
		delete(additionalProperties, "ReferenceCustomer")
		delete(additionalProperties, "ContactBan")
		delete(additionalProperties, "ExternalCustomerID")
		delete(additionalProperties, "ExternalID")
		delete(additionalProperties, "ExternalCustomerExternalID")
		delete(additionalProperties, "ExternalSourceCustomerID")
		delete(additionalProperties, "ExternalOrderType")
		delete(additionalProperties, "ExternalType")
		delete(additionalProperties, "ExternalOrderAccountID")
		delete(additionalProperties, "ExternalAccountID")
		delete(additionalProperties, "ExternalOrderSubAccountID")
		delete(additionalProperties, "ExternalSourceID")
		delete(additionalProperties, "Marketplace")
		delete(additionalProperties, "TestUser")
		delete(additionalProperties, "Newsletter")
		delete(additionalProperties, "Segment")
		delete(additionalProperties, "CreationDate")
		delete(additionalProperties, "ModificationDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerV4 struct {
	value *CustomerV4
	isSet bool
}

func (v NullableCustomerV4) Get() *CustomerV4 {
	return v.value
}

func (v *NullableCustomerV4) Set(val *CustomerV4) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerV4) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerV4(val *CustomerV4) *NullableCustomerV4 {
	return &NullableCustomerV4{value: val, isSet: true}
}

func (v NullableCustomerV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


