/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// TaxClass the model 'TaxClass'
type TaxClass string

// List of TaxClass
const (
	TAXCLASS_NORMAL_TAX TaxClass = "NormalTax"
	TAXCLASS_REDUCED_TAX TaxClass = "ReducedTax"
	TAXCLASS_HIGHLY_REDUCED_TAX TaxClass = "HighlyReducedTax"
	TAXCLASS_NO_TAX TaxClass = "NoTax"
)

// All allowed values of TaxClass enum
var AllowedTaxClassEnumValues = []TaxClass{
	"NormalTax",
	"ReducedTax",
	"HighlyReducedTax",
	"NoTax",
}

func (v *TaxClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TaxClass(value)
	for _, existing := range AllowedTaxClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TaxClass", value)
}

// NewTaxClassFromValue returns a pointer to a valid TaxClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTaxClassFromValue(v string) (*TaxClass, error) {
	ev := TaxClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TaxClass: valid values are %v", v, AllowedTaxClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TaxClass) IsValid() bool {
	for _, existing := range AllowedTaxClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TaxClass value
func (v TaxClass) Ptr() *TaxClass {
	return &v
}

type NullableTaxClass struct {
	value *TaxClass
	isSet bool
}

func (v NullableTaxClass) Get() *TaxClass {
	return v.value
}

func (v *NullableTaxClass) Set(val *TaxClass) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxClass) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxClass(val *TaxClass) *NullableTaxClass {
	return &NullableTaxClass{value: val, isSet: true}
}

func (v NullableTaxClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

