/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the TranslatedString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranslatedString{}

// TranslatedString struct for TranslatedString
type TranslatedString struct {
	De string `json:"de"`
	En string `json:"en"`
	AdditionalProperties map[string]interface{}
}

type _TranslatedString TranslatedString

// NewTranslatedString instantiates a new TranslatedString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranslatedString(de string, en string) *TranslatedString {
	this := TranslatedString{}
	this.De = de
	this.En = en
	return &this
}

// NewTranslatedStringWithDefaults instantiates a new TranslatedString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranslatedStringWithDefaults() *TranslatedString {
	this := TranslatedString{}
	return &this
}

// GetDe returns the De field value
func (o *TranslatedString) GetDe() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.De
}

// GetDeOk returns a tuple with the De field value
// and a boolean to check if the value has been set.
func (o *TranslatedString) GetDeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.De, true
}

// SetDe sets field value
func (o *TranslatedString) SetDe(v string) {
	o.De = v
}

// GetEn returns the En field value
func (o *TranslatedString) GetEn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.En
}

// GetEnOk returns a tuple with the En field value
// and a boolean to check if the value has been set.
func (o *TranslatedString) GetEnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.En, true
}

// SetEn sets field value
func (o *TranslatedString) SetEn(v string) {
	o.En = v
}

func (o TranslatedString) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranslatedString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["de"] = o.De
	toSerialize["en"] = o.En

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TranslatedString) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"de",
		"en",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTranslatedString := _TranslatedString{}

	err = json.Unmarshal(data, &varTranslatedString)

	if err != nil {
		return err
	}

	*o = TranslatedString(varTranslatedString)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "de")
		delete(additionalProperties, "en")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTranslatedString struct {
	value *TranslatedString
	isSet bool
}

func (v NullableTranslatedString) Get() *TranslatedString {
	return v.value
}

func (v *NullableTranslatedString) Set(val *TranslatedString) {
	v.value = val
	v.isSet = true
}

func (v NullableTranslatedString) IsSet() bool {
	return v.isSet
}

func (v *NullableTranslatedString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranslatedString(val *TranslatedString) *NullableTranslatedString {
	return &NullableTranslatedString{value: val, isSet: true}
}

func (v NullableTranslatedString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranslatedString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


