/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// ReceiptStatusV4 the model 'ReceiptStatusV4'
type ReceiptStatusV4 string

// List of ReceiptStatusV4
const (
	RECEIPTSTATUSV4_OPEN ReceiptStatusV4 = "Open"
	RECEIPTSTATUSV4_IN_PROGRESS ReceiptStatusV4 = "InProgress"
	RECEIPTSTATUSV4_COMPLETED ReceiptStatusV4 = "Completed"
	RECEIPTSTATUSV4_CANCELLED ReceiptStatusV4 = "Cancelled"
)

// All allowed values of ReceiptStatusV4 enum
var AllowedReceiptStatusV4EnumValues = []ReceiptStatusV4{
	"Open",
	"InProgress",
	"Completed",
	"Cancelled",
}

func (v *ReceiptStatusV4) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReceiptStatusV4(value)
	for _, existing := range AllowedReceiptStatusV4EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReceiptStatusV4", value)
}

// NewReceiptStatusV4FromValue returns a pointer to a valid ReceiptStatusV4
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReceiptStatusV4FromValue(v string) (*ReceiptStatusV4, error) {
	ev := ReceiptStatusV4(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReceiptStatusV4: valid values are %v", v, AllowedReceiptStatusV4EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReceiptStatusV4) IsValid() bool {
	for _, existing := range AllowedReceiptStatusV4EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReceiptStatusV4 value
func (v ReceiptStatusV4) Ptr() *ReceiptStatusV4 {
	return &v
}

type NullableReceiptStatusV4 struct {
	value *ReceiptStatusV4
	isSet bool
}

func (v NullableReceiptStatusV4) Get() *ReceiptStatusV4 {
	return v.value
}

func (v *NullableReceiptStatusV4) Set(val *ReceiptStatusV4) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptStatusV4) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptStatusV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptStatusV4(val *ReceiptStatusV4) *NullableReceiptStatusV4 {
	return &NullableReceiptStatusV4{value: val, isSet: true}
}

func (v NullableReceiptStatusV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptStatusV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

