/*
Customa

E-Commerce BI & CRM Tool

API version: 3.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ReceiptSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptSearchResponse{}

// ReceiptSearchResponse struct for ReceiptSearchResponse
type ReceiptSearchResponse struct {
	// Total number of items.
	TotalCount int32 `json:"TotalCount"`
	// Current page number.
	CurrentPage int32 `json:"CurrentPage"`
	// Total number of pages.
	PagesCount int32 `json:"PagesCount"`
	// Number of items per page.
	PageSize int32 `json:"PageSize"`
	// List of receipts.
	Receipts []StrictReceipt `json:"Receipts"`
	AdditionalProperties map[string]interface{}
}

type _ReceiptSearchResponse ReceiptSearchResponse

// NewReceiptSearchResponse instantiates a new ReceiptSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptSearchResponse(totalCount int32, currentPage int32, pagesCount int32, pageSize int32, receipts []StrictReceipt) *ReceiptSearchResponse {
	this := ReceiptSearchResponse{}
	this.TotalCount = totalCount
	this.CurrentPage = currentPage
	this.PagesCount = pagesCount
	this.PageSize = pageSize
	this.Receipts = receipts
	return &this
}

// NewReceiptSearchResponseWithDefaults instantiates a new ReceiptSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptSearchResponseWithDefaults() *ReceiptSearchResponse {
	this := ReceiptSearchResponse{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *ReceiptSearchResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ReceiptSearchResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetCurrentPage returns the CurrentPage field value
func (o *ReceiptSearchResponse) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponse) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *ReceiptSearchResponse) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetPagesCount returns the PagesCount field value
func (o *ReceiptSearchResponse) GetPagesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PagesCount
}

// GetPagesCountOk returns a tuple with the PagesCount field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponse) GetPagesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PagesCount, true
}

// SetPagesCount sets field value
func (o *ReceiptSearchResponse) SetPagesCount(v int32) {
	o.PagesCount = v
}

// GetPageSize returns the PageSize field value
func (o *ReceiptSearchResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ReceiptSearchResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetReceipts returns the Receipts field value
func (o *ReceiptSearchResponse) GetReceipts() []StrictReceipt {
	if o == nil {
		var ret []StrictReceipt
		return ret
	}

	return o.Receipts
}

// GetReceiptsOk returns a tuple with the Receipts field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponse) GetReceiptsOk() ([]StrictReceipt, bool) {
	if o == nil {
		return nil, false
	}
	return o.Receipts, true
}

// SetReceipts sets field value
func (o *ReceiptSearchResponse) SetReceipts(v []StrictReceipt) {
	o.Receipts = v
}

func (o ReceiptSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TotalCount"] = o.TotalCount
	toSerialize["CurrentPage"] = o.CurrentPage
	toSerialize["PagesCount"] = o.PagesCount
	toSerialize["PageSize"] = o.PageSize
	toSerialize["Receipts"] = o.Receipts

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReceiptSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotalCount",
		"CurrentPage",
		"PagesCount",
		"PageSize",
		"Receipts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptSearchResponse := _ReceiptSearchResponse{}

	err = json.Unmarshal(data, &varReceiptSearchResponse)

	if err != nil {
		return err
	}

	*o = ReceiptSearchResponse(varReceiptSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "TotalCount")
		delete(additionalProperties, "CurrentPage")
		delete(additionalProperties, "PagesCount")
		delete(additionalProperties, "PageSize")
		delete(additionalProperties, "Receipts")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReceiptSearchResponse struct {
	value *ReceiptSearchResponse
	isSet bool
}

func (v NullableReceiptSearchResponse) Get() *ReceiptSearchResponse {
	return v.value
}

func (v *NullableReceiptSearchResponse) Set(val *ReceiptSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptSearchResponse(val *ReceiptSearchResponse) *NullableReceiptSearchResponse {
	return &NullableReceiptSearchResponse{value: val, isSet: true}
}

func (v NullableReceiptSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


