/*
Customa

E-Commerce BI & CRM Tool

API version: 3.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the TrafficFiltersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficFiltersResponse{}

// TrafficFiltersResponse struct for TrafficFiltersResponse
type TrafficFiltersResponse struct {
	// Available grouping options. Key is display label, value is the grouping identifier.
	Groupings map[string]string `json:"Groupings"`
	// Available data sources. Key is display label, value is the source identifier.
	Sources map[string]string `json:"Sources"`
	// Available marketplaces. Key is display label, value is the marketplace ID as string.
	Marketplaces map[string]string `json:"Marketplaces"`
	// Available campaigns. Key is campaign name, value is the campaign ID as string.
	Campaigns map[string]string `json:"Campaigns"`
	AdditionalProperties map[string]interface{}
}

type _TrafficFiltersResponse TrafficFiltersResponse

// NewTrafficFiltersResponse instantiates a new TrafficFiltersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficFiltersResponse(groupings map[string]string, sources map[string]string, marketplaces map[string]string, campaigns map[string]string) *TrafficFiltersResponse {
	this := TrafficFiltersResponse{}
	this.Groupings = groupings
	this.Sources = sources
	this.Marketplaces = marketplaces
	this.Campaigns = campaigns
	return &this
}

// NewTrafficFiltersResponseWithDefaults instantiates a new TrafficFiltersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficFiltersResponseWithDefaults() *TrafficFiltersResponse {
	this := TrafficFiltersResponse{}
	return &this
}

// GetGroupings returns the Groupings field value
func (o *TrafficFiltersResponse) GetGroupings() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Groupings
}

// GetGroupingsOk returns a tuple with the Groupings field value
// and a boolean to check if the value has been set.
func (o *TrafficFiltersResponse) GetGroupingsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Groupings, true
}

// SetGroupings sets field value
func (o *TrafficFiltersResponse) SetGroupings(v map[string]string) {
	o.Groupings = v
}

// GetSources returns the Sources field value
func (o *TrafficFiltersResponse) GetSources() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *TrafficFiltersResponse) GetSourcesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sources, true
}

// SetSources sets field value
func (o *TrafficFiltersResponse) SetSources(v map[string]string) {
	o.Sources = v
}

// GetMarketplaces returns the Marketplaces field value
func (o *TrafficFiltersResponse) GetMarketplaces() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Marketplaces
}

// GetMarketplacesOk returns a tuple with the Marketplaces field value
// and a boolean to check if the value has been set.
func (o *TrafficFiltersResponse) GetMarketplacesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Marketplaces, true
}

// SetMarketplaces sets field value
func (o *TrafficFiltersResponse) SetMarketplaces(v map[string]string) {
	o.Marketplaces = v
}

// GetCampaigns returns the Campaigns field value
func (o *TrafficFiltersResponse) GetCampaigns() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Campaigns
}

// GetCampaignsOk returns a tuple with the Campaigns field value
// and a boolean to check if the value has been set.
func (o *TrafficFiltersResponse) GetCampaignsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Campaigns, true
}

// SetCampaigns sets field value
func (o *TrafficFiltersResponse) SetCampaigns(v map[string]string) {
	o.Campaigns = v
}

func (o TrafficFiltersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficFiltersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Groupings"] = o.Groupings
	toSerialize["Sources"] = o.Sources
	toSerialize["Marketplaces"] = o.Marketplaces
	toSerialize["Campaigns"] = o.Campaigns

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TrafficFiltersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Groupings",
		"Sources",
		"Marketplaces",
		"Campaigns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrafficFiltersResponse := _TrafficFiltersResponse{}

	err = json.Unmarshal(data, &varTrafficFiltersResponse)

	if err != nil {
		return err
	}

	*o = TrafficFiltersResponse(varTrafficFiltersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Groupings")
		delete(additionalProperties, "Sources")
		delete(additionalProperties, "Marketplaces")
		delete(additionalProperties, "Campaigns")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTrafficFiltersResponse struct {
	value *TrafficFiltersResponse
	isSet bool
}

func (v NullableTrafficFiltersResponse) Get() *TrafficFiltersResponse {
	return v.value
}

func (v *NullableTrafficFiltersResponse) Set(val *TrafficFiltersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficFiltersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficFiltersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficFiltersResponse(val *TrafficFiltersResponse) *NullableTrafficFiltersResponse {
	return &NullableTrafficFiltersResponse{value: val, isSet: true}
}

func (v NullableTrafficFiltersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficFiltersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


