/*
Customa

E-Commerce BI & CRM Tool

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthLoginRequestV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLoginRequestV3{}

// AuthLoginRequestV3 Request body for authentication.
type AuthLoginRequestV3 struct {
	// Username (E-Mail address) used for authentication with Customa.
	Username string `json:"Username"`
	// Password for the User.
	Password string `json:"Password"`
	// ID of the project the user is authenticating for.
	Project int32 `json:"Project"`
	AdditionalProperties map[string]interface{}
}

type _AuthLoginRequestV3 AuthLoginRequestV3

// NewAuthLoginRequestV3 instantiates a new AuthLoginRequestV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLoginRequestV3(username string, password string, project int32) *AuthLoginRequestV3 {
	this := AuthLoginRequestV3{}
	this.Username = username
	this.Password = password
	this.Project = project
	return &this
}

// NewAuthLoginRequestV3WithDefaults instantiates a new AuthLoginRequestV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginRequestV3WithDefaults() *AuthLoginRequestV3 {
	this := AuthLoginRequestV3{}
	return &this
}

// GetUsername returns the Username field value
func (o *AuthLoginRequestV3) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *AuthLoginRequestV3) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *AuthLoginRequestV3) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *AuthLoginRequestV3) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthLoginRequestV3) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthLoginRequestV3) SetPassword(v string) {
	o.Password = v
}

// GetProject returns the Project field value
func (o *AuthLoginRequestV3) GetProject() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *AuthLoginRequestV3) GetProjectOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *AuthLoginRequestV3) SetProject(v int32) {
	o.Project = v
}

func (o AuthLoginRequestV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLoginRequestV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Username"] = o.Username
	toSerialize["Password"] = o.Password
	toSerialize["Project"] = o.Project

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthLoginRequestV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Username",
		"Password",
		"Project",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthLoginRequestV3 := _AuthLoginRequestV3{}

	err = json.Unmarshal(data, &varAuthLoginRequestV3)

	if err != nil {
		return err
	}

	*o = AuthLoginRequestV3(varAuthLoginRequestV3)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Username")
		delete(additionalProperties, "Password")
		delete(additionalProperties, "Project")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthLoginRequestV3 struct {
	value *AuthLoginRequestV3
	isSet bool
}

func (v NullableAuthLoginRequestV3) Get() *AuthLoginRequestV3 {
	return v.value
}

func (v *NullableAuthLoginRequestV3) Set(val *AuthLoginRequestV3) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginRequestV3) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginRequestV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginRequestV3(val *AuthLoginRequestV3) *NullableAuthLoginRequestV3 {
	return &NullableAuthLoginRequestV3{value: val, isSet: true}
}

func (v NullableAuthLoginRequestV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginRequestV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


