/*
Customa

E-Commerce BI & CRM Tool

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsReceiptResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsReceiptResponse{}

// StatsReceiptResponse Response containing statistics on receipts.
type StatsReceiptResponse struct {
	// List of groups with statistics.
	Groups []StatsReceiptResponseGroupsInner `json:"Groups"`
	AdditionalProperties map[string]interface{}
}

type _StatsReceiptResponse StatsReceiptResponse

// NewStatsReceiptResponse instantiates a new StatsReceiptResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsReceiptResponse(groups []StatsReceiptResponseGroupsInner) *StatsReceiptResponse {
	this := StatsReceiptResponse{}
	this.Groups = groups
	return &this
}

// NewStatsReceiptResponseWithDefaults instantiates a new StatsReceiptResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsReceiptResponseWithDefaults() *StatsReceiptResponse {
	this := StatsReceiptResponse{}
	return &this
}

// GetGroups returns the Groups field value
func (o *StatsReceiptResponse) GetGroups() []StatsReceiptResponseGroupsInner {
	if o == nil {
		var ret []StatsReceiptResponseGroupsInner
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptResponse) GetGroupsOk() ([]StatsReceiptResponseGroupsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *StatsReceiptResponse) SetGroups(v []StatsReceiptResponseGroupsInner) {
	o.Groups = v
}

func (o StatsReceiptResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsReceiptResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Groups"] = o.Groups

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsReceiptResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsReceiptResponse := _StatsReceiptResponse{}

	err = json.Unmarshal(data, &varStatsReceiptResponse)

	if err != nil {
		return err
	}

	*o = StatsReceiptResponse(varStatsReceiptResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Groups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsReceiptResponse struct {
	value *StatsReceiptResponse
	isSet bool
}

func (v NullableStatsReceiptResponse) Get() *StatsReceiptResponse {
	return v.value
}

func (v *NullableStatsReceiptResponse) Set(val *StatsReceiptResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsReceiptResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsReceiptResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsReceiptResponse(val *StatsReceiptResponse) *NullableStatsReceiptResponse {
	return &NullableStatsReceiptResponse{value: val, isSet: true}
}

func (v NullableStatsReceiptResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsReceiptResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


