/*
Customa

E-Commerce BI & CRM Tool

API version: 3.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ItemCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemCreatedResponse{}

// ItemCreatedResponse struct for ItemCreatedResponse
type ItemCreatedResponse struct {
	// ID of the created Item.
	ID string `json:"ID"`
	AdditionalProperties map[string]interface{}
}

type _ItemCreatedResponse ItemCreatedResponse

// NewItemCreatedResponse instantiates a new ItemCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemCreatedResponse(iD string) *ItemCreatedResponse {
	this := ItemCreatedResponse{}
	this.ID = iD
	return &this
}

// NewItemCreatedResponseWithDefaults instantiates a new ItemCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemCreatedResponseWithDefaults() *ItemCreatedResponse {
	this := ItemCreatedResponse{}
	return &this
}

// GetID returns the ID field value
func (o *ItemCreatedResponse) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *ItemCreatedResponse) GetIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *ItemCreatedResponse) SetID(v string) {
	o.ID = v
}

func (o ItemCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ItemCreatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemCreatedResponse := _ItemCreatedResponse{}

	err = json.Unmarshal(data, &varItemCreatedResponse)

	if err != nil {
		return err
	}

	*o = ItemCreatedResponse(varItemCreatedResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ID")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableItemCreatedResponse struct {
	value *ItemCreatedResponse
	isSet bool
}

func (v NullableItemCreatedResponse) Get() *ItemCreatedResponse {
	return v.value
}

func (v *NullableItemCreatedResponse) Set(val *ItemCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableItemCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableItemCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemCreatedResponse(val *ItemCreatedResponse) *NullableItemCreatedResponse {
	return &NullableItemCreatedResponse{value: val, isSet: true}
}

func (v NullableItemCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


