/*
Customa

E-Commerce BI & CRM Tool

API version: 3.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsReceiptItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsReceiptItemResponse{}

// StatsReceiptItemResponse Response containing statistics on receipt items.
type StatsReceiptItemResponse struct {
	// List of groups with statistics.
	Groups []StatsReceiptItemResponseGroupsInner `json:"Groups"`
	AdditionalProperties map[string]interface{}
}

type _StatsReceiptItemResponse StatsReceiptItemResponse

// NewStatsReceiptItemResponse instantiates a new StatsReceiptItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsReceiptItemResponse(groups []StatsReceiptItemResponseGroupsInner) *StatsReceiptItemResponse {
	this := StatsReceiptItemResponse{}
	this.Groups = groups
	return &this
}

// NewStatsReceiptItemResponseWithDefaults instantiates a new StatsReceiptItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsReceiptItemResponseWithDefaults() *StatsReceiptItemResponse {
	this := StatsReceiptItemResponse{}
	return &this
}

// GetGroups returns the Groups field value
func (o *StatsReceiptItemResponse) GetGroups() []StatsReceiptItemResponseGroupsInner {
	if o == nil {
		var ret []StatsReceiptItemResponseGroupsInner
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptItemResponse) GetGroupsOk() ([]StatsReceiptItemResponseGroupsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *StatsReceiptItemResponse) SetGroups(v []StatsReceiptItemResponseGroupsInner) {
	o.Groups = v
}

func (o StatsReceiptItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsReceiptItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Groups"] = o.Groups

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsReceiptItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsReceiptItemResponse := _StatsReceiptItemResponse{}

	err = json.Unmarshal(data, &varStatsReceiptItemResponse)

	if err != nil {
		return err
	}

	*o = StatsReceiptItemResponse(varStatsReceiptItemResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Groups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsReceiptItemResponse struct {
	value *StatsReceiptItemResponse
	isSet bool
}

func (v NullableStatsReceiptItemResponse) Get() *StatsReceiptItemResponse {
	return v.value
}

func (v *NullableStatsReceiptItemResponse) Set(val *StatsReceiptItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsReceiptItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsReceiptItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsReceiptItemResponse(val *StatsReceiptItemResponse) *NullableStatsReceiptItemResponse {
	return &NullableStatsReceiptItemResponse{value: val, isSet: true}
}

func (v NullableStatsReceiptItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsReceiptItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


