/*
Customa

E-Commerce BI & CRM Tool

API version: 3.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// SegmentCondition the model 'SegmentCondition'
type SegmentCondition string

// List of SegmentCondition
const (
	SEGMENTCONDITION_GREATER_THAN SegmentCondition = "GreaterThan"
	SEGMENTCONDITION_GREATER_THAN_OR_EQUAL SegmentCondition = "GreaterThanOrEqual"
	SEGMENTCONDITION_LESS_THAN SegmentCondition = "LessThan"
	SEGMENTCONDITION_LESS_THAN_OR_EQUAL SegmentCondition = "LessThanOrEqual"
	SEGMENTCONDITION_EQUAL SegmentCondition = "Equal"
	SEGMENTCONDITION_UNDEFINED SegmentCondition = "Undefined"
)

// All allowed values of SegmentCondition enum
var AllowedSegmentConditionEnumValues = []SegmentCondition{
	"GreaterThan",
	"GreaterThanOrEqual",
	"LessThan",
	"LessThanOrEqual",
	"Equal",
	"Undefined",
}

func (v *SegmentCondition) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SegmentCondition(value)
	for _, existing := range AllowedSegmentConditionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SegmentCondition", value)
}

// NewSegmentConditionFromValue returns a pointer to a valid SegmentCondition
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSegmentConditionFromValue(v string) (*SegmentCondition, error) {
	ev := SegmentCondition(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SegmentCondition: valid values are %v", v, AllowedSegmentConditionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SegmentCondition) IsValid() bool {
	for _, existing := range AllowedSegmentConditionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SegmentCondition value
func (v SegmentCondition) Ptr() *SegmentCondition {
	return &v
}

type NullableSegmentCondition struct {
	value *SegmentCondition
	isSet bool
}

func (v NullableSegmentCondition) Get() *SegmentCondition {
	return v.value
}

func (v *NullableSegmentCondition) Set(val *SegmentCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableSegmentCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableSegmentCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegmentCondition(val *SegmentCondition) *NullableSegmentCondition {
	return &NullableSegmentCondition{value: val, isSet: true}
}

func (v NullableSegmentCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegmentCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

