/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// ProductSetMode the model 'ProductSetMode'
type ProductSetMode string

// List of ProductSetMode
const (
	PRODUCTSETMODE_SETS ProductSetMode = "Sets"
	PRODUCTSETMODE_PARTS ProductSetMode = "Parts"
)

// All allowed values of ProductSetMode enum
var AllowedProductSetModeEnumValues = []ProductSetMode{
	"Sets",
	"Parts",
}

func (v *ProductSetMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProductSetMode(value)
	for _, existing := range AllowedProductSetModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProductSetMode", value)
}

// NewProductSetModeFromValue returns a pointer to a valid ProductSetMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProductSetModeFromValue(v string) (*ProductSetMode, error) {
	ev := ProductSetMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProductSetMode: valid values are %v", v, AllowedProductSetModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProductSetMode) IsValid() bool {
	for _, existing := range AllowedProductSetModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProductSetMode value
func (v ProductSetMode) Ptr() *ProductSetMode {
	return &v
}

type NullableProductSetMode struct {
	value *ProductSetMode
	isSet bool
}

func (v NullableProductSetMode) Get() *ProductSetMode {
	return v.value
}

func (v *NullableProductSetMode) Set(val *ProductSetMode) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSetMode) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSetMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSetMode(val *ProductSetMode) *NullableProductSetMode {
	return &NullableProductSetMode{value: val, isSet: true}
}

func (v NullableProductSetMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSetMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

