/*
Customa

E-Commerce BI & CRM Tool

API version: 3.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the Segment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Segment{}

// Segment A single customer segment generated from the segment definition.
type Segment struct {
	Frequency SegmentValue `json:"Frequency"`
	Monetary SegmentValue `json:"Monetary"`
	CustomerLifetimeValue SegmentValue `json:"CustomerLifetimeValue"`
	Recency int32 `json:"Recency"`
	Description string `json:"Description"`
	AdditionalProperties map[string]interface{}
}

type _Segment Segment

// NewSegment instantiates a new Segment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSegment(frequency SegmentValue, monetary SegmentValue, customerLifetimeValue SegmentValue, recency int32, description string) *Segment {
	this := Segment{}
	this.Frequency = frequency
	this.Monetary = monetary
	this.CustomerLifetimeValue = customerLifetimeValue
	this.Recency = recency
	this.Description = description
	return &this
}

// NewSegmentWithDefaults instantiates a new Segment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSegmentWithDefaults() *Segment {
	this := Segment{}
	return &this
}

// GetFrequency returns the Frequency field value
func (o *Segment) GetFrequency() SegmentValue {
	if o == nil {
		var ret SegmentValue
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *Segment) GetFrequencyOk() (*SegmentValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *Segment) SetFrequency(v SegmentValue) {
	o.Frequency = v
}

// GetMonetary returns the Monetary field value
func (o *Segment) GetMonetary() SegmentValue {
	if o == nil {
		var ret SegmentValue
		return ret
	}

	return o.Monetary
}

// GetMonetaryOk returns a tuple with the Monetary field value
// and a boolean to check if the value has been set.
func (o *Segment) GetMonetaryOk() (*SegmentValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Monetary, true
}

// SetMonetary sets field value
func (o *Segment) SetMonetary(v SegmentValue) {
	o.Monetary = v
}

// GetCustomerLifetimeValue returns the CustomerLifetimeValue field value
func (o *Segment) GetCustomerLifetimeValue() SegmentValue {
	if o == nil {
		var ret SegmentValue
		return ret
	}

	return o.CustomerLifetimeValue
}

// GetCustomerLifetimeValueOk returns a tuple with the CustomerLifetimeValue field value
// and a boolean to check if the value has been set.
func (o *Segment) GetCustomerLifetimeValueOk() (*SegmentValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerLifetimeValue, true
}

// SetCustomerLifetimeValue sets field value
func (o *Segment) SetCustomerLifetimeValue(v SegmentValue) {
	o.CustomerLifetimeValue = v
}

// GetRecency returns the Recency field value
func (o *Segment) GetRecency() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Recency
}

// GetRecencyOk returns a tuple with the Recency field value
// and a boolean to check if the value has been set.
func (o *Segment) GetRecencyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recency, true
}

// SetRecency sets field value
func (o *Segment) SetRecency(v int32) {
	o.Recency = v
}

// GetDescription returns the Description field value
func (o *Segment) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Segment) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Segment) SetDescription(v string) {
	o.Description = v
}

func (o Segment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Segment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Frequency"] = o.Frequency
	toSerialize["Monetary"] = o.Monetary
	toSerialize["CustomerLifetimeValue"] = o.CustomerLifetimeValue
	toSerialize["Recency"] = o.Recency
	toSerialize["Description"] = o.Description

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Segment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Frequency",
		"Monetary",
		"CustomerLifetimeValue",
		"Recency",
		"Description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSegment := _Segment{}

	err = json.Unmarshal(data, &varSegment)

	if err != nil {
		return err
	}

	*o = Segment(varSegment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Frequency")
		delete(additionalProperties, "Monetary")
		delete(additionalProperties, "CustomerLifetimeValue")
		delete(additionalProperties, "Recency")
		delete(additionalProperties, "Description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSegment struct {
	value *Segment
	isSet bool
}

func (v NullableSegment) Get() *Segment {
	return v.value
}

func (v *NullableSegment) Set(val *Segment) {
	v.value = val
	v.isSet = true
}

func (v NullableSegment) IsSet() bool {
	return v.isSet
}

func (v *NullableSegment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegment(val *Segment) *NullableSegment {
	return &NullableSegment{value: val, isSet: true}
}

func (v NullableSegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


