/*
Customa

E-Commerce BI & CRM Tool

API version: 3.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductSetPartV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSetPartV4{}

// ProductSetPartV4 struct for ProductSetPartV4
type ProductSetPartV4 struct {
	ProductID string `json:"ProductID"`
	Quantity int32 `json:"Quantity"`
	AdditionalProperties map[string]interface{}
}

type _ProductSetPartV4 ProductSetPartV4

// NewProductSetPartV4 instantiates a new ProductSetPartV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSetPartV4(productID string, quantity int32) *ProductSetPartV4 {
	this := ProductSetPartV4{}
	this.ProductID = productID
	this.Quantity = quantity
	return &this
}

// NewProductSetPartV4WithDefaults instantiates a new ProductSetPartV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSetPartV4WithDefaults() *ProductSetPartV4 {
	this := ProductSetPartV4{}
	return &this
}

// GetProductID returns the ProductID field value
func (o *ProductSetPartV4) GetProductID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductID
}

// GetProductIDOk returns a tuple with the ProductID field value
// and a boolean to check if the value has been set.
func (o *ProductSetPartV4) GetProductIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductID, true
}

// SetProductID sets field value
func (o *ProductSetPartV4) SetProductID(v string) {
	o.ProductID = v
}

// GetQuantity returns the Quantity field value
func (o *ProductSetPartV4) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ProductSetPartV4) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ProductSetPartV4) SetQuantity(v int32) {
	o.Quantity = v
}

func (o ProductSetPartV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSetPartV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ProductID"] = o.ProductID
	toSerialize["Quantity"] = o.Quantity

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductSetPartV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ProductID",
		"Quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductSetPartV4 := _ProductSetPartV4{}

	err = json.Unmarshal(data, &varProductSetPartV4)

	if err != nil {
		return err
	}

	*o = ProductSetPartV4(varProductSetPartV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ProductID")
		delete(additionalProperties, "Quantity")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductSetPartV4 struct {
	value *ProductSetPartV4
	isSet bool
}

func (v NullableProductSetPartV4) Get() *ProductSetPartV4 {
	return v.value
}

func (v *NullableProductSetPartV4) Set(val *ProductSetPartV4) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSetPartV4) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSetPartV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSetPartV4(val *ProductSetPartV4) *NullableProductSetPartV4 {
	return &NullableProductSetPartV4{value: val, isSet: true}
}

func (v NullableProductSetPartV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSetPartV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


