/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ReceiptSearchResponseV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptSearchResponseV4{}

// ReceiptSearchResponseV4 struct for ReceiptSearchResponseV4
type ReceiptSearchResponseV4 struct {
	Receipts []ReceiptV4 `json:"Receipts,omitempty"`
	// Total number of items.
	TotalCount int32 `json:"TotalCount"`
	// Current page number.
	CurrentPage int32 `json:"CurrentPage"`
	// Total number of pages.
	PagesCount int32 `json:"PagesCount"`
	// Number of items per page.
	PageSize int32 `json:"PageSize"`
	AdditionalProperties map[string]interface{}
}

type _ReceiptSearchResponseV4 ReceiptSearchResponseV4

// NewReceiptSearchResponseV4 instantiates a new ReceiptSearchResponseV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptSearchResponseV4(totalCount int32, currentPage int32, pagesCount int32, pageSize int32) *ReceiptSearchResponseV4 {
	this := ReceiptSearchResponseV4{}
	this.TotalCount = totalCount
	this.CurrentPage = currentPage
	this.PagesCount = pagesCount
	this.PageSize = pageSize
	return &this
}

// NewReceiptSearchResponseV4WithDefaults instantiates a new ReceiptSearchResponseV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptSearchResponseV4WithDefaults() *ReceiptSearchResponseV4 {
	this := ReceiptSearchResponseV4{}
	return &this
}

// GetReceipts returns the Receipts field value if set, zero value otherwise.
func (o *ReceiptSearchResponseV4) GetReceipts() []ReceiptV4 {
	if o == nil || IsNil(o.Receipts) {
		var ret []ReceiptV4
		return ret
	}
	return o.Receipts
}

// GetReceiptsOk returns a tuple with the Receipts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponseV4) GetReceiptsOk() ([]ReceiptV4, bool) {
	if o == nil || IsNil(o.Receipts) {
		return nil, false
	}
	return o.Receipts, true
}

// HasReceipts returns a boolean if a field has been set.
func (o *ReceiptSearchResponseV4) HasReceipts() bool {
	if o != nil && !IsNil(o.Receipts) {
		return true
	}

	return false
}

// SetReceipts gets a reference to the given []ReceiptV4 and assigns it to the Receipts field.
func (o *ReceiptSearchResponseV4) SetReceipts(v []ReceiptV4) {
	o.Receipts = v
}

// GetTotalCount returns the TotalCount field value
func (o *ReceiptSearchResponseV4) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponseV4) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ReceiptSearchResponseV4) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetCurrentPage returns the CurrentPage field value
func (o *ReceiptSearchResponseV4) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponseV4) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *ReceiptSearchResponseV4) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetPagesCount returns the PagesCount field value
func (o *ReceiptSearchResponseV4) GetPagesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PagesCount
}

// GetPagesCountOk returns a tuple with the PagesCount field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponseV4) GetPagesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PagesCount, true
}

// SetPagesCount sets field value
func (o *ReceiptSearchResponseV4) SetPagesCount(v int32) {
	o.PagesCount = v
}

// GetPageSize returns the PageSize field value
func (o *ReceiptSearchResponseV4) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ReceiptSearchResponseV4) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ReceiptSearchResponseV4) SetPageSize(v int32) {
	o.PageSize = v
}

func (o ReceiptSearchResponseV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptSearchResponseV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Receipts) {
		toSerialize["Receipts"] = o.Receipts
	}
	toSerialize["TotalCount"] = o.TotalCount
	toSerialize["CurrentPage"] = o.CurrentPage
	toSerialize["PagesCount"] = o.PagesCount
	toSerialize["PageSize"] = o.PageSize

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReceiptSearchResponseV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotalCount",
		"CurrentPage",
		"PagesCount",
		"PageSize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptSearchResponseV4 := _ReceiptSearchResponseV4{}

	err = json.Unmarshal(data, &varReceiptSearchResponseV4)

	if err != nil {
		return err
	}

	*o = ReceiptSearchResponseV4(varReceiptSearchResponseV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Receipts")
		delete(additionalProperties, "TotalCount")
		delete(additionalProperties, "CurrentPage")
		delete(additionalProperties, "PagesCount")
		delete(additionalProperties, "PageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReceiptSearchResponseV4 struct {
	value *ReceiptSearchResponseV4
	isSet bool
}

func (v NullableReceiptSearchResponseV4) Get() *ReceiptSearchResponseV4 {
	return v.value
}

func (v *NullableReceiptSearchResponseV4) Set(val *ReceiptSearchResponseV4) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptSearchResponseV4) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptSearchResponseV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptSearchResponseV4(val *ReceiptSearchResponseV4) *NullableReceiptSearchResponseV4 {
	return &NullableReceiptSearchResponseV4{value: val, isSet: true}
}

func (v NullableReceiptSearchResponseV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptSearchResponseV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


