/*
Customa

E-Commerce BI & CRM Tool

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsReceiptResponseGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsReceiptResponseGroupsInner{}

// StatsReceiptResponseGroupsInner Group with statistics. 
type StatsReceiptResponseGroupsInner struct {
	// Key for the group, use this when processing the response client-side.
	GroupKey string `json:"GroupKey"`
	// Group name, only used for display. _Never_ use this for anything else than display.
	GroupName string `json:"GroupName"`
	// List of receipt types with statistics.
	Types []StatsReceiptResponseGroupsInnerTypesInner `json:"Types"`
	AdditionalProperties map[string]interface{}
}

type _StatsReceiptResponseGroupsInner StatsReceiptResponseGroupsInner

// NewStatsReceiptResponseGroupsInner instantiates a new StatsReceiptResponseGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsReceiptResponseGroupsInner(groupKey string, groupName string, types []StatsReceiptResponseGroupsInnerTypesInner) *StatsReceiptResponseGroupsInner {
	this := StatsReceiptResponseGroupsInner{}
	this.GroupKey = groupKey
	this.GroupName = groupName
	this.Types = types
	return &this
}

// NewStatsReceiptResponseGroupsInnerWithDefaults instantiates a new StatsReceiptResponseGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsReceiptResponseGroupsInnerWithDefaults() *StatsReceiptResponseGroupsInner {
	this := StatsReceiptResponseGroupsInner{}
	return &this
}

// GetGroupKey returns the GroupKey field value
func (o *StatsReceiptResponseGroupsInner) GetGroupKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupKey
}

// GetGroupKeyOk returns a tuple with the GroupKey field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptResponseGroupsInner) GetGroupKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupKey, true
}

// SetGroupKey sets field value
func (o *StatsReceiptResponseGroupsInner) SetGroupKey(v string) {
	o.GroupKey = v
}

// GetGroupName returns the GroupName field value
func (o *StatsReceiptResponseGroupsInner) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptResponseGroupsInner) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *StatsReceiptResponseGroupsInner) SetGroupName(v string) {
	o.GroupName = v
}

// GetTypes returns the Types field value
func (o *StatsReceiptResponseGroupsInner) GetTypes() []StatsReceiptResponseGroupsInnerTypesInner {
	if o == nil {
		var ret []StatsReceiptResponseGroupsInnerTypesInner
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptResponseGroupsInner) GetTypesOk() ([]StatsReceiptResponseGroupsInnerTypesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *StatsReceiptResponseGroupsInner) SetTypes(v []StatsReceiptResponseGroupsInnerTypesInner) {
	o.Types = v
}

func (o StatsReceiptResponseGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsReceiptResponseGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["GroupKey"] = o.GroupKey
	toSerialize["GroupName"] = o.GroupName
	toSerialize["Types"] = o.Types

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsReceiptResponseGroupsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"GroupKey",
		"GroupName",
		"Types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsReceiptResponseGroupsInner := _StatsReceiptResponseGroupsInner{}

	err = json.Unmarshal(data, &varStatsReceiptResponseGroupsInner)

	if err != nil {
		return err
	}

	*o = StatsReceiptResponseGroupsInner(varStatsReceiptResponseGroupsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "GroupKey")
		delete(additionalProperties, "GroupName")
		delete(additionalProperties, "Types")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsReceiptResponseGroupsInner struct {
	value *StatsReceiptResponseGroupsInner
	isSet bool
}

func (v NullableStatsReceiptResponseGroupsInner) Get() *StatsReceiptResponseGroupsInner {
	return v.value
}

func (v *NullableStatsReceiptResponseGroupsInner) Set(val *StatsReceiptResponseGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsReceiptResponseGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsReceiptResponseGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsReceiptResponseGroupsInner(val *StatsReceiptResponseGroupsInner) *NullableStatsReceiptResponseGroupsInner {
	return &NullableStatsReceiptResponseGroupsInner{value: val, isSet: true}
}

func (v NullableStatsReceiptResponseGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsReceiptResponseGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


