/*
Customa

E-Commerce BI & CRM Tool

API version: 3.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// Salutation the model 'Salutation'
type Salutation string

// List of Salutation
const (
	SALUTATION_M Salutation = "m"
	SALUTATION_F Salutation = "f"
	SALUTATION_X Salutation = "x"
)

// All allowed values of Salutation enum
var AllowedSalutationEnumValues = []Salutation{
	"m",
	"f",
	"x",
}

func (v *Salutation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Salutation(value)
	for _, existing := range AllowedSalutationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Salutation", value)
}

// NewSalutationFromValue returns a pointer to a valid Salutation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSalutationFromValue(v string) (*Salutation, error) {
	ev := Salutation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Salutation: valid values are %v", v, AllowedSalutationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Salutation) IsValid() bool {
	for _, existing := range AllowedSalutationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Salutation value
func (v Salutation) Ptr() *Salutation {
	return &v
}

type NullableSalutation struct {
	value *Salutation
	isSet bool
}

func (v NullableSalutation) Get() *Salutation {
	return v.value
}

func (v *NullableSalutation) Set(val *Salutation) {
	v.value = val
	v.isSet = true
}

func (v NullableSalutation) IsSet() bool {
	return v.isSet
}

func (v *NullableSalutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalutation(val *Salutation) *NullableSalutation {
	return &NullableSalutation{value: val, isSet: true}
}

func (v NullableSalutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

