/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the ItemCreatedResponse2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemCreatedResponse2{}

// ItemCreatedResponse2 Response body after successfully creating a new item.
type ItemCreatedResponse2 struct {
	ID string `json:"ID"`
	AdditionalProperties map[string]interface{}
}

type _ItemCreatedResponse2 ItemCreatedResponse2

// NewItemCreatedResponse2 instantiates a new ItemCreatedResponse2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemCreatedResponse2(iD string) *ItemCreatedResponse2 {
	this := ItemCreatedResponse2{}
	this.ID = iD
	return &this
}

// NewItemCreatedResponse2WithDefaults instantiates a new ItemCreatedResponse2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemCreatedResponse2WithDefaults() *ItemCreatedResponse2 {
	this := ItemCreatedResponse2{}
	return &this
}

// GetID returns the ID field value
func (o *ItemCreatedResponse2) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *ItemCreatedResponse2) GetIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *ItemCreatedResponse2) SetID(v string) {
	o.ID = v
}

func (o ItemCreatedResponse2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemCreatedResponse2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ID"] = o.ID

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ItemCreatedResponse2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemCreatedResponse2 := _ItemCreatedResponse2{}

	err = json.Unmarshal(data, &varItemCreatedResponse2)

	if err != nil {
		return err
	}

	*o = ItemCreatedResponse2(varItemCreatedResponse2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ID")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableItemCreatedResponse2 struct {
	value *ItemCreatedResponse2
	isSet bool
}

func (v NullableItemCreatedResponse2) Get() *ItemCreatedResponse2 {
	return v.value
}

func (v *NullableItemCreatedResponse2) Set(val *ItemCreatedResponse2) {
	v.value = val
	v.isSet = true
}

func (v NullableItemCreatedResponse2) IsSet() bool {
	return v.isSet
}

func (v *NullableItemCreatedResponse2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemCreatedResponse2(val *ItemCreatedResponse2) *NullableItemCreatedResponse2 {
	return &NullableItemCreatedResponse2{value: val, isSet: true}
}

func (v NullableItemCreatedResponse2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemCreatedResponse2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


