/*
Customa

E-Commerce BI & CRM Tool

API version: 3.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsReceiptItemResponseGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsReceiptItemResponseGroupsInner{}

// StatsReceiptItemResponseGroupsInner Group with statistics. 
type StatsReceiptItemResponseGroupsInner struct {
	// Key for the group, use this when processing the response client-side.
	GroupKey string `json:"GroupKey"`
	// Group name, only used for display. _Never_ use this for anything else than display.
	GroupName string `json:"GroupName"`
	// List of receipt types with statistics.
	Types []StatsReceiptItemResponseGroupsInnerTypesInner `json:"Types"`
	AdditionalProperties map[string]interface{}
}

type _StatsReceiptItemResponseGroupsInner StatsReceiptItemResponseGroupsInner

// NewStatsReceiptItemResponseGroupsInner instantiates a new StatsReceiptItemResponseGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsReceiptItemResponseGroupsInner(groupKey string, groupName string, types []StatsReceiptItemResponseGroupsInnerTypesInner) *StatsReceiptItemResponseGroupsInner {
	this := StatsReceiptItemResponseGroupsInner{}
	this.GroupKey = groupKey
	this.GroupName = groupName
	this.Types = types
	return &this
}

// NewStatsReceiptItemResponseGroupsInnerWithDefaults instantiates a new StatsReceiptItemResponseGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsReceiptItemResponseGroupsInnerWithDefaults() *StatsReceiptItemResponseGroupsInner {
	this := StatsReceiptItemResponseGroupsInner{}
	return &this
}

// GetGroupKey returns the GroupKey field value
func (o *StatsReceiptItemResponseGroupsInner) GetGroupKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupKey
}

// GetGroupKeyOk returns a tuple with the GroupKey field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptItemResponseGroupsInner) GetGroupKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupKey, true
}

// SetGroupKey sets field value
func (o *StatsReceiptItemResponseGroupsInner) SetGroupKey(v string) {
	o.GroupKey = v
}

// GetGroupName returns the GroupName field value
func (o *StatsReceiptItemResponseGroupsInner) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptItemResponseGroupsInner) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *StatsReceiptItemResponseGroupsInner) SetGroupName(v string) {
	o.GroupName = v
}

// GetTypes returns the Types field value
func (o *StatsReceiptItemResponseGroupsInner) GetTypes() []StatsReceiptItemResponseGroupsInnerTypesInner {
	if o == nil {
		var ret []StatsReceiptItemResponseGroupsInnerTypesInner
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *StatsReceiptItemResponseGroupsInner) GetTypesOk() ([]StatsReceiptItemResponseGroupsInnerTypesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *StatsReceiptItemResponseGroupsInner) SetTypes(v []StatsReceiptItemResponseGroupsInnerTypesInner) {
	o.Types = v
}

func (o StatsReceiptItemResponseGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsReceiptItemResponseGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["GroupKey"] = o.GroupKey
	toSerialize["GroupName"] = o.GroupName
	toSerialize["Types"] = o.Types

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsReceiptItemResponseGroupsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"GroupKey",
		"GroupName",
		"Types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsReceiptItemResponseGroupsInner := _StatsReceiptItemResponseGroupsInner{}

	err = json.Unmarshal(data, &varStatsReceiptItemResponseGroupsInner)

	if err != nil {
		return err
	}

	*o = StatsReceiptItemResponseGroupsInner(varStatsReceiptItemResponseGroupsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "GroupKey")
		delete(additionalProperties, "GroupName")
		delete(additionalProperties, "Types")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsReceiptItemResponseGroupsInner struct {
	value *StatsReceiptItemResponseGroupsInner
	isSet bool
}

func (v NullableStatsReceiptItemResponseGroupsInner) Get() *StatsReceiptItemResponseGroupsInner {
	return v.value
}

func (v *NullableStatsReceiptItemResponseGroupsInner) Set(val *StatsReceiptItemResponseGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsReceiptItemResponseGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsReceiptItemResponseGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsReceiptItemResponseGroupsInner(val *StatsReceiptItemResponseGroupsInner) *NullableStatsReceiptItemResponseGroupsInner {
	return &NullableStatsReceiptItemResponseGroupsInner{value: val, isSet: true}
}

func (v NullableStatsReceiptItemResponseGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsReceiptItemResponseGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


