/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// FilterType the model 'FilterType'
type FilterType string

// List of FilterType
const (
	FILTERTYPE_IS_EMPTY FilterType = "IsEmpty"
	FILTERTYPE_IS_NOT_EMPTY FilterType = "IsNotEmpty"
	FILTERTYPE_MATCH FilterType = "Match"
	FILTERTYPE_MATCH_PREFIX FilterType = "MatchPrefix"
	FILTERTYPE_MATCH_SUFFIX FilterType = "MatchSuffix"
	FILTERTYPE_MATCH_INFIX FilterType = "MatchInfix"
	FILTERTYPE_LESS_THAN FilterType = "LessThan"
	FILTERTYPE_LESS_THAN_OR_EQUAL FilterType = "LessThanOrEqual"
	FILTERTYPE_GREATER_THAN FilterType = "GreaterThan"
	FILTERTYPE_GREATER_THAN_OR_EQUAL FilterType = "GreaterThanOrEqual"
)

// All allowed values of FilterType enum
var AllowedFilterTypeEnumValues = []FilterType{
	"IsEmpty",
	"IsNotEmpty",
	"Match",
	"MatchPrefix",
	"MatchSuffix",
	"MatchInfix",
	"LessThan",
	"LessThanOrEqual",
	"GreaterThan",
	"GreaterThanOrEqual",
}

func (v *FilterType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FilterType(value)
	for _, existing := range AllowedFilterTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FilterType", value)
}

// NewFilterTypeFromValue returns a pointer to a valid FilterType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFilterTypeFromValue(v string) (*FilterType, error) {
	ev := FilterType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FilterType: valid values are %v", v, AllowedFilterTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FilterType) IsValid() bool {
	for _, existing := range AllowedFilterTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FilterType value
func (v FilterType) Ptr() *FilterType {
	return &v
}

type NullableFilterType struct {
	value *FilterType
	isSet bool
}

func (v NullableFilterType) Get() *FilterType {
	return v.value
}

func (v *NullableFilterType) Set(val *FilterType) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterType) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterType(val *FilterType) *NullableFilterType {
	return &NullableFilterType{value: val, isSet: true}
}

func (v NullableFilterType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

