/*
Customa

E-Commerce BI & CRM Tool

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the StrictReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrictReceipt{}

// StrictReceipt struct for StrictReceipt
type StrictReceipt struct {
	// Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
	CreationDate *time.Time `json:"CreationDate,omitempty"`
	// Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
	ModificationDate *time.Time `json:"ModificationDate,omitempty"`
	// ID of the receipt. Set internally by Customa, any given value is ignored.
	ID *string `json:"ID,omitempty"`
	// Type of the receipt.
	Type string `json:"Type"`
	// Receipt number
	Number string `json:"Number"`
	// ID of the customer.
	CustomerID string `json:"CustomerID"`
	ExternalOrderType string `json:"ExternalOrderType"`
	ExternalOrderID NullableInt32 `json:"ExternalOrderID"`
	ExternalOrderExternalID NullableString `json:"ExternalOrderExternalID"`
	ExternalOrderAccountID int32 `json:"ExternalOrderAccountID"`
	ExternalOrderSubAccountID string `json:"ExternalOrderSubAccountID"`
	// Marketplace of the receipt.
	Marketplace *string `json:"Marketplace,omitempty"`
	// Purchase date of the receipt.
	PurchaseDate time.Time `json:"PurchaseDate"`
	// Delivery date of the receipt. Will be removed in Q1 2026. Please use ReceiptDate instead.
	// Deprecated
	DeliveryDate NullableTime `json:"DeliveryDate,omitempty"`
	// Date of the receipt.
	ReceiptDate NullableTime `json:"ReceiptDate"`
	// Referrer (last cookie) of the customer when creating this receipt.
	Referrer NullableString `json:"Referrer"`
	// Referrer Channel of the customer when creating this receipt.
	ReferrerChannel NullableString `json:"ReferrerChannel"`
	// Payment method of the receipt.
	PaymentMethod string `json:"PaymentMethod"`
	RevenueNet Price `json:"RevenueNet"`
	RevenueGross Price `json:"RevenueGross"`
	// Status of the receipt.
	ReceiptStatus string `json:"ReceiptStatus"`
	// Payment status of the receipt.
	PaymentStatus string `json:"PaymentStatus"`
	// Delivery status of the receipt.
	DeliveryStatus string `json:"DeliveryStatus"`
	// Google Click ID of this receipt.
	GoogleClickID NullableString `json:"GoogleClickID"`
	// List of items in the receipt.
	Items []StrictReceiptItem `json:"Items"`
	// Additional field data for the receipt.
	AdditionalFields []AdditionalField `json:"AdditionalFields"`
	AdditionalProperties map[string]interface{}
}

type _StrictReceipt StrictReceipt

// NewStrictReceipt instantiates a new StrictReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrictReceipt(type_ string, number string, customerID string, externalOrderType string, externalOrderID NullableInt32, externalOrderExternalID NullableString, externalOrderAccountID int32, externalOrderSubAccountID string, purchaseDate time.Time, receiptDate NullableTime, referrer NullableString, referrerChannel NullableString, paymentMethod string, revenueNet Price, revenueGross Price, receiptStatus string, paymentStatus string, deliveryStatus string, googleClickID NullableString, items []StrictReceiptItem, additionalFields []AdditionalField) *StrictReceipt {
	this := StrictReceipt{}
	this.Type = type_
	this.Number = number
	this.CustomerID = customerID
	this.ExternalOrderType = externalOrderType
	this.ExternalOrderID = externalOrderID
	this.ExternalOrderExternalID = externalOrderExternalID
	this.ExternalOrderAccountID = externalOrderAccountID
	this.ExternalOrderSubAccountID = externalOrderSubAccountID
	this.PurchaseDate = purchaseDate
	this.ReceiptDate = receiptDate
	this.Referrer = referrer
	this.ReferrerChannel = referrerChannel
	this.PaymentMethod = paymentMethod
	this.RevenueNet = revenueNet
	this.RevenueGross = revenueGross
	this.ReceiptStatus = receiptStatus
	this.PaymentStatus = paymentStatus
	this.DeliveryStatus = deliveryStatus
	this.GoogleClickID = googleClickID
	this.Items = items
	this.AdditionalFields = additionalFields
	return &this
}

// NewStrictReceiptWithDefaults instantiates a new StrictReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrictReceiptWithDefaults() *StrictReceipt {
	this := StrictReceipt{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *StrictReceipt) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *StrictReceipt) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given time.Time and assigns it to the CreationDate field.
func (o *StrictReceipt) SetCreationDate(v time.Time) {
	o.CreationDate = &v
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise.
func (o *StrictReceipt) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetModificationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModificationDate) {
		return nil, false
	}
	return o.ModificationDate, true
}

// HasModificationDate returns a boolean if a field has been set.
func (o *StrictReceipt) HasModificationDate() bool {
	if o != nil && !IsNil(o.ModificationDate) {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given time.Time and assigns it to the ModificationDate field.
func (o *StrictReceipt) SetModificationDate(v time.Time) {
	o.ModificationDate = &v
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *StrictReceipt) GetID() string {
	if o == nil || IsNil(o.ID) {
		var ret string
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetIDOk() (*string, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *StrictReceipt) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given string and assigns it to the ID field.
func (o *StrictReceipt) SetID(v string) {
	o.ID = &v
}

// GetType returns the Type field value
func (o *StrictReceipt) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StrictReceipt) SetType(v string) {
	o.Type = v
}

// GetNumber returns the Number field value
func (o *StrictReceipt) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *StrictReceipt) SetNumber(v string) {
	o.Number = v
}

// GetCustomerID returns the CustomerID field value
func (o *StrictReceipt) GetCustomerID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerID
}

// GetCustomerIDOk returns a tuple with the CustomerID field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetCustomerIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerID, true
}

// SetCustomerID sets field value
func (o *StrictReceipt) SetCustomerID(v string) {
	o.CustomerID = v
}

// GetExternalOrderType returns the ExternalOrderType field value
func (o *StrictReceipt) GetExternalOrderType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalOrderType
}

// GetExternalOrderTypeOk returns a tuple with the ExternalOrderType field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetExternalOrderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderType, true
}

// SetExternalOrderType sets field value
func (o *StrictReceipt) SetExternalOrderType(v string) {
	o.ExternalOrderType = v
}

// GetExternalOrderID returns the ExternalOrderID field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *StrictReceipt) GetExternalOrderID() int32 {
	if o == nil || o.ExternalOrderID.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ExternalOrderID.Get()
}

// GetExternalOrderIDOk returns a tuple with the ExternalOrderID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetExternalOrderIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderID.Get(), o.ExternalOrderID.IsSet()
}

// SetExternalOrderID sets field value
func (o *StrictReceipt) SetExternalOrderID(v int32) {
	o.ExternalOrderID.Set(&v)
}

// GetExternalOrderExternalID returns the ExternalOrderExternalID field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StrictReceipt) GetExternalOrderExternalID() string {
	if o == nil || o.ExternalOrderExternalID.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExternalOrderExternalID.Get()
}

// GetExternalOrderExternalIDOk returns a tuple with the ExternalOrderExternalID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetExternalOrderExternalIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderExternalID.Get(), o.ExternalOrderExternalID.IsSet()
}

// SetExternalOrderExternalID sets field value
func (o *StrictReceipt) SetExternalOrderExternalID(v string) {
	o.ExternalOrderExternalID.Set(&v)
}

// GetExternalOrderAccountID returns the ExternalOrderAccountID field value
func (o *StrictReceipt) GetExternalOrderAccountID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExternalOrderAccountID
}

// GetExternalOrderAccountIDOk returns a tuple with the ExternalOrderAccountID field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetExternalOrderAccountIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderAccountID, true
}

// SetExternalOrderAccountID sets field value
func (o *StrictReceipt) SetExternalOrderAccountID(v int32) {
	o.ExternalOrderAccountID = v
}

// GetExternalOrderSubAccountID returns the ExternalOrderSubAccountID field value
func (o *StrictReceipt) GetExternalOrderSubAccountID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalOrderSubAccountID
}

// GetExternalOrderSubAccountIDOk returns a tuple with the ExternalOrderSubAccountID field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetExternalOrderSubAccountIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalOrderSubAccountID, true
}

// SetExternalOrderSubAccountID sets field value
func (o *StrictReceipt) SetExternalOrderSubAccountID(v string) {
	o.ExternalOrderSubAccountID = v
}

// GetMarketplace returns the Marketplace field value if set, zero value otherwise.
func (o *StrictReceipt) GetMarketplace() string {
	if o == nil || IsNil(o.Marketplace) {
		var ret string
		return ret
	}
	return *o.Marketplace
}

// GetMarketplaceOk returns a tuple with the Marketplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetMarketplaceOk() (*string, bool) {
	if o == nil || IsNil(o.Marketplace) {
		return nil, false
	}
	return o.Marketplace, true
}

// HasMarketplace returns a boolean if a field has been set.
func (o *StrictReceipt) HasMarketplace() bool {
	if o != nil && !IsNil(o.Marketplace) {
		return true
	}

	return false
}

// SetMarketplace gets a reference to the given string and assigns it to the Marketplace field.
func (o *StrictReceipt) SetMarketplace(v string) {
	o.Marketplace = &v
}

// GetPurchaseDate returns the PurchaseDate field value
func (o *StrictReceipt) GetPurchaseDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PurchaseDate
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetPurchaseDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PurchaseDate, true
}

// SetPurchaseDate sets field value
func (o *StrictReceipt) SetPurchaseDate(v time.Time) {
	o.PurchaseDate = v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *StrictReceipt) GetDeliveryDate() time.Time {
	if o == nil || IsNil(o.DeliveryDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeliveryDate.Get()
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *StrictReceipt) GetDeliveryDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeliveryDate.Get(), o.DeliveryDate.IsSet()
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *StrictReceipt) HasDeliveryDate() bool {
	if o != nil && o.DeliveryDate.IsSet() {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given NullableTime and assigns it to the DeliveryDate field.
// Deprecated
func (o *StrictReceipt) SetDeliveryDate(v time.Time) {
	o.DeliveryDate.Set(&v)
}
// SetDeliveryDateNil sets the value for DeliveryDate to be an explicit nil
func (o *StrictReceipt) SetDeliveryDateNil() {
	o.DeliveryDate.Set(nil)
}

// UnsetDeliveryDate ensures that no value is present for DeliveryDate, not even an explicit nil
func (o *StrictReceipt) UnsetDeliveryDate() {
	o.DeliveryDate.Unset()
}

// GetReceiptDate returns the ReceiptDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *StrictReceipt) GetReceiptDate() time.Time {
	if o == nil || o.ReceiptDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ReceiptDate.Get()
}

// GetReceiptDateOk returns a tuple with the ReceiptDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetReceiptDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceiptDate.Get(), o.ReceiptDate.IsSet()
}

// SetReceiptDate sets field value
func (o *StrictReceipt) SetReceiptDate(v time.Time) {
	o.ReceiptDate.Set(&v)
}

// GetReferrer returns the Referrer field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StrictReceipt) GetReferrer() string {
	if o == nil || o.Referrer.Get() == nil {
		var ret string
		return ret
	}

	return *o.Referrer.Get()
}

// GetReferrerOk returns a tuple with the Referrer field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetReferrerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Referrer.Get(), o.Referrer.IsSet()
}

// SetReferrer sets field value
func (o *StrictReceipt) SetReferrer(v string) {
	o.Referrer.Set(&v)
}

// GetReferrerChannel returns the ReferrerChannel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StrictReceipt) GetReferrerChannel() string {
	if o == nil || o.ReferrerChannel.Get() == nil {
		var ret string
		return ret
	}

	return *o.ReferrerChannel.Get()
}

// GetReferrerChannelOk returns a tuple with the ReferrerChannel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetReferrerChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferrerChannel.Get(), o.ReferrerChannel.IsSet()
}

// SetReferrerChannel sets field value
func (o *StrictReceipt) SetReferrerChannel(v string) {
	o.ReferrerChannel.Set(&v)
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *StrictReceipt) GetPaymentMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetPaymentMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *StrictReceipt) SetPaymentMethod(v string) {
	o.PaymentMethod = v
}

// GetRevenueNet returns the RevenueNet field value
func (o *StrictReceipt) GetRevenueNet() Price {
	if o == nil {
		var ret Price
		return ret
	}

	return o.RevenueNet
}

// GetRevenueNetOk returns a tuple with the RevenueNet field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetRevenueNetOk() (*Price, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevenueNet, true
}

// SetRevenueNet sets field value
func (o *StrictReceipt) SetRevenueNet(v Price) {
	o.RevenueNet = v
}

// GetRevenueGross returns the RevenueGross field value
func (o *StrictReceipt) GetRevenueGross() Price {
	if o == nil {
		var ret Price
		return ret
	}

	return o.RevenueGross
}

// GetRevenueGrossOk returns a tuple with the RevenueGross field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetRevenueGrossOk() (*Price, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevenueGross, true
}

// SetRevenueGross sets field value
func (o *StrictReceipt) SetRevenueGross(v Price) {
	o.RevenueGross = v
}

// GetReceiptStatus returns the ReceiptStatus field value
func (o *StrictReceipt) GetReceiptStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiptStatus
}

// GetReceiptStatusOk returns a tuple with the ReceiptStatus field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetReceiptStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptStatus, true
}

// SetReceiptStatus sets field value
func (o *StrictReceipt) SetReceiptStatus(v string) {
	o.ReceiptStatus = v
}

// GetPaymentStatus returns the PaymentStatus field value
func (o *StrictReceipt) GetPaymentStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentStatus
}

// GetPaymentStatusOk returns a tuple with the PaymentStatus field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetPaymentStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentStatus, true
}

// SetPaymentStatus sets field value
func (o *StrictReceipt) SetPaymentStatus(v string) {
	o.PaymentStatus = v
}

// GetDeliveryStatus returns the DeliveryStatus field value
func (o *StrictReceipt) GetDeliveryStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeliveryStatus
}

// GetDeliveryStatusOk returns a tuple with the DeliveryStatus field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetDeliveryStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryStatus, true
}

// SetDeliveryStatus sets field value
func (o *StrictReceipt) SetDeliveryStatus(v string) {
	o.DeliveryStatus = v
}

// GetGoogleClickID returns the GoogleClickID field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StrictReceipt) GetGoogleClickID() string {
	if o == nil || o.GoogleClickID.Get() == nil {
		var ret string
		return ret
	}

	return *o.GoogleClickID.Get()
}

// GetGoogleClickIDOk returns a tuple with the GoogleClickID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrictReceipt) GetGoogleClickIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GoogleClickID.Get(), o.GoogleClickID.IsSet()
}

// SetGoogleClickID sets field value
func (o *StrictReceipt) SetGoogleClickID(v string) {
	o.GoogleClickID.Set(&v)
}

// GetItems returns the Items field value
func (o *StrictReceipt) GetItems() []StrictReceiptItem {
	if o == nil {
		var ret []StrictReceiptItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetItemsOk() ([]StrictReceiptItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *StrictReceipt) SetItems(v []StrictReceiptItem) {
	o.Items = v
}

// GetAdditionalFields returns the AdditionalFields field value
func (o *StrictReceipt) GetAdditionalFields() []AdditionalField {
	if o == nil {
		var ret []AdditionalField
		return ret
	}

	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value
// and a boolean to check if the value has been set.
func (o *StrictReceipt) GetAdditionalFieldsOk() ([]AdditionalField, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdditionalFields, true
}

// SetAdditionalFields sets field value
func (o *StrictReceipt) SetAdditionalFields(v []AdditionalField) {
	o.AdditionalFields = v
}

func (o StrictReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrictReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.ModificationDate) {
		toSerialize["ModificationDate"] = o.ModificationDate
	}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	toSerialize["Type"] = o.Type
	toSerialize["Number"] = o.Number
	toSerialize["CustomerID"] = o.CustomerID
	toSerialize["ExternalOrderType"] = o.ExternalOrderType
	toSerialize["ExternalOrderID"] = o.ExternalOrderID.Get()
	toSerialize["ExternalOrderExternalID"] = o.ExternalOrderExternalID.Get()
	toSerialize["ExternalOrderAccountID"] = o.ExternalOrderAccountID
	toSerialize["ExternalOrderSubAccountID"] = o.ExternalOrderSubAccountID
	if !IsNil(o.Marketplace) {
		toSerialize["Marketplace"] = o.Marketplace
	}
	toSerialize["PurchaseDate"] = o.PurchaseDate
	if o.DeliveryDate.IsSet() {
		toSerialize["DeliveryDate"] = o.DeliveryDate.Get()
	}
	toSerialize["ReceiptDate"] = o.ReceiptDate.Get()
	toSerialize["Referrer"] = o.Referrer.Get()
	toSerialize["ReferrerChannel"] = o.ReferrerChannel.Get()
	toSerialize["PaymentMethod"] = o.PaymentMethod
	toSerialize["RevenueNet"] = o.RevenueNet
	toSerialize["RevenueGross"] = o.RevenueGross
	toSerialize["ReceiptStatus"] = o.ReceiptStatus
	toSerialize["PaymentStatus"] = o.PaymentStatus
	toSerialize["DeliveryStatus"] = o.DeliveryStatus
	toSerialize["GoogleClickID"] = o.GoogleClickID.Get()
	toSerialize["Items"] = o.Items
	toSerialize["AdditionalFields"] = o.AdditionalFields

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrictReceipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Type",
		"Number",
		"CustomerID",
		"ExternalOrderType",
		"ExternalOrderID",
		"ExternalOrderExternalID",
		"ExternalOrderAccountID",
		"ExternalOrderSubAccountID",
		"PurchaseDate",
		"ReceiptDate",
		"Referrer",
		"ReferrerChannel",
		"PaymentMethod",
		"RevenueNet",
		"RevenueGross",
		"ReceiptStatus",
		"PaymentStatus",
		"DeliveryStatus",
		"GoogleClickID",
		"Items",
		"AdditionalFields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrictReceipt := _StrictReceipt{}

	err = json.Unmarshal(data, &varStrictReceipt)

	if err != nil {
		return err
	}

	*o = StrictReceipt(varStrictReceipt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "CreationDate")
		delete(additionalProperties, "ModificationDate")
		delete(additionalProperties, "ID")
		delete(additionalProperties, "Type")
		delete(additionalProperties, "Number")
		delete(additionalProperties, "CustomerID")
		delete(additionalProperties, "ExternalOrderType")
		delete(additionalProperties, "ExternalOrderID")
		delete(additionalProperties, "ExternalOrderExternalID")
		delete(additionalProperties, "ExternalOrderAccountID")
		delete(additionalProperties, "ExternalOrderSubAccountID")
		delete(additionalProperties, "Marketplace")
		delete(additionalProperties, "PurchaseDate")
		delete(additionalProperties, "DeliveryDate")
		delete(additionalProperties, "ReceiptDate")
		delete(additionalProperties, "Referrer")
		delete(additionalProperties, "ReferrerChannel")
		delete(additionalProperties, "PaymentMethod")
		delete(additionalProperties, "RevenueNet")
		delete(additionalProperties, "RevenueGross")
		delete(additionalProperties, "ReceiptStatus")
		delete(additionalProperties, "PaymentStatus")
		delete(additionalProperties, "DeliveryStatus")
		delete(additionalProperties, "GoogleClickID")
		delete(additionalProperties, "Items")
		delete(additionalProperties, "AdditionalFields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrictReceipt struct {
	value *StrictReceipt
	isSet bool
}

func (v NullableStrictReceipt) Get() *StrictReceipt {
	return v.value
}

func (v *NullableStrictReceipt) Set(val *StrictReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullableStrictReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableStrictReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrictReceipt(val *StrictReceipt) *NullableStrictReceipt {
	return &NullableStrictReceipt{value: val, isSet: true}
}

func (v NullableStrictReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrictReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


