/*
Customa

E-Commerce BI & CRM Tool

API version: 3.13.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CategoryV4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryV4{}

// CategoryV4 struct for CategoryV4
type CategoryV4 struct {
	// ID of the category. Set internally by Customa, any given value is ignored.
	ID NullableString `json:"ID,omitempty"`
	// Name of the category.
	Name string `json:"Name"`
	// ID of the parent category. Must not create a circular reference.
	Parent NullableString `json:"Parent,omitempty"`
	// Hierarchy level of the category. 0 for root categories. Set internally by Customa, any given value is ignored.
	Level NullableInt32 `json:"Level,omitempty"`
	// Additional field data for the category.
	AdditionalFields []string `json:"AdditionalFields"`
	// Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
	CreationDate NullableTime `json:"CreationDate,omitempty"`
	// Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
	ModificationDate NullableTime `json:"ModificationDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CategoryV4 CategoryV4

// NewCategoryV4 instantiates a new CategoryV4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryV4(name string, additionalFields []string) *CategoryV4 {
	this := CategoryV4{}
	this.Name = name
	this.AdditionalFields = additionalFields
	return &this
}

// NewCategoryV4WithDefaults instantiates a new CategoryV4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryV4WithDefaults() *CategoryV4 {
	this := CategoryV4{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryV4) GetID() string {
	if o == nil || IsNil(o.ID.Get()) {
		var ret string
		return ret
	}
	return *o.ID.Get()
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryV4) GetIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ID.Get(), o.ID.IsSet()
}

// HasID returns a boolean if a field has been set.
func (o *CategoryV4) HasID() bool {
	if o != nil && o.ID.IsSet() {
		return true
	}

	return false
}

// SetID gets a reference to the given NullableString and assigns it to the ID field.
func (o *CategoryV4) SetID(v string) {
	o.ID.Set(&v)
}
// SetIDNil sets the value for ID to be an explicit nil
func (o *CategoryV4) SetIDNil() {
	o.ID.Set(nil)
}

// UnsetID ensures that no value is present for ID, not even an explicit nil
func (o *CategoryV4) UnsetID() {
	o.ID.Unset()
}

// GetName returns the Name field value
func (o *CategoryV4) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CategoryV4) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CategoryV4) SetName(v string) {
	o.Name = v
}

// GetParent returns the Parent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryV4) GetParent() string {
	if o == nil || IsNil(o.Parent.Get()) {
		var ret string
		return ret
	}
	return *o.Parent.Get()
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryV4) GetParentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Parent.Get(), o.Parent.IsSet()
}

// HasParent returns a boolean if a field has been set.
func (o *CategoryV4) HasParent() bool {
	if o != nil && o.Parent.IsSet() {
		return true
	}

	return false
}

// SetParent gets a reference to the given NullableString and assigns it to the Parent field.
func (o *CategoryV4) SetParent(v string) {
	o.Parent.Set(&v)
}
// SetParentNil sets the value for Parent to be an explicit nil
func (o *CategoryV4) SetParentNil() {
	o.Parent.Set(nil)
}

// UnsetParent ensures that no value is present for Parent, not even an explicit nil
func (o *CategoryV4) UnsetParent() {
	o.Parent.Unset()
}

// GetLevel returns the Level field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryV4) GetLevel() int32 {
	if o == nil || IsNil(o.Level.Get()) {
		var ret int32
		return ret
	}
	return *o.Level.Get()
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryV4) GetLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Level.Get(), o.Level.IsSet()
}

// HasLevel returns a boolean if a field has been set.
func (o *CategoryV4) HasLevel() bool {
	if o != nil && o.Level.IsSet() {
		return true
	}

	return false
}

// SetLevel gets a reference to the given NullableInt32 and assigns it to the Level field.
func (o *CategoryV4) SetLevel(v int32) {
	o.Level.Set(&v)
}
// SetLevelNil sets the value for Level to be an explicit nil
func (o *CategoryV4) SetLevelNil() {
	o.Level.Set(nil)
}

// UnsetLevel ensures that no value is present for Level, not even an explicit nil
func (o *CategoryV4) UnsetLevel() {
	o.Level.Unset()
}

// GetAdditionalFields returns the AdditionalFields field value
func (o *CategoryV4) GetAdditionalFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value
// and a boolean to check if the value has been set.
func (o *CategoryV4) GetAdditionalFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdditionalFields, true
}

// SetAdditionalFields sets field value
func (o *CategoryV4) SetAdditionalFields(v []string) {
	o.AdditionalFields = v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryV4) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate.Get()
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryV4) GetCreationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreationDate.Get(), o.CreationDate.IsSet()
}

// HasCreationDate returns a boolean if a field has been set.
func (o *CategoryV4) HasCreationDate() bool {
	if o != nil && o.CreationDate.IsSet() {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given NullableTime and assigns it to the CreationDate field.
func (o *CategoryV4) SetCreationDate(v time.Time) {
	o.CreationDate.Set(&v)
}
// SetCreationDateNil sets the value for CreationDate to be an explicit nil
func (o *CategoryV4) SetCreationDateNil() {
	o.CreationDate.Set(nil)
}

// UnsetCreationDate ensures that no value is present for CreationDate, not even an explicit nil
func (o *CategoryV4) UnsetCreationDate() {
	o.CreationDate.Unset()
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CategoryV4) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate.Get()
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CategoryV4) GetModificationDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModificationDate.Get(), o.ModificationDate.IsSet()
}

// HasModificationDate returns a boolean if a field has been set.
func (o *CategoryV4) HasModificationDate() bool {
	if o != nil && o.ModificationDate.IsSet() {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given NullableTime and assigns it to the ModificationDate field.
func (o *CategoryV4) SetModificationDate(v time.Time) {
	o.ModificationDate.Set(&v)
}
// SetModificationDateNil sets the value for ModificationDate to be an explicit nil
func (o *CategoryV4) SetModificationDateNil() {
	o.ModificationDate.Set(nil)
}

// UnsetModificationDate ensures that no value is present for ModificationDate, not even an explicit nil
func (o *CategoryV4) UnsetModificationDate() {
	o.ModificationDate.Unset()
}

func (o CategoryV4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryV4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ID.IsSet() {
		toSerialize["ID"] = o.ID.Get()
	}
	toSerialize["Name"] = o.Name
	if o.Parent.IsSet() {
		toSerialize["Parent"] = o.Parent.Get()
	}
	if o.Level.IsSet() {
		toSerialize["Level"] = o.Level.Get()
	}
	toSerialize["AdditionalFields"] = o.AdditionalFields
	if o.CreationDate.IsSet() {
		toSerialize["CreationDate"] = o.CreationDate.Get()
	}
	if o.ModificationDate.IsSet() {
		toSerialize["ModificationDate"] = o.ModificationDate.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CategoryV4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
		"AdditionalFields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryV4 := _CategoryV4{}

	err = json.Unmarshal(data, &varCategoryV4)

	if err != nil {
		return err
	}

	*o = CategoryV4(varCategoryV4)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ID")
		delete(additionalProperties, "Name")
		delete(additionalProperties, "Parent")
		delete(additionalProperties, "Level")
		delete(additionalProperties, "AdditionalFields")
		delete(additionalProperties, "CreationDate")
		delete(additionalProperties, "ModificationDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCategoryV4 struct {
	value *CategoryV4
	isSet bool
}

func (v NullableCategoryV4) Get() *CategoryV4 {
	return v.value
}

func (v *NullableCategoryV4) Set(val *CategoryV4) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryV4) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryV4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryV4(val *CategoryV4) *NullableCategoryV4 {
	return &NullableCategoryV4{value: val, isSet: true}
}

func (v NullableCategoryV4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryV4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


