/*
Customa

E-Commerce BI & CRM Tool

API version: 3.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"fmt"
)

// checks if the StatsGroupings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsGroupings{}

// StatsGroupings struct for StatsGroupings
type StatsGroupings struct {
	Groupings map[string]string `json:"Groupings"`
	AdditionalProperties map[string]interface{}
}

type _StatsGroupings StatsGroupings

// NewStatsGroupings instantiates a new StatsGroupings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsGroupings(groupings map[string]string) *StatsGroupings {
	this := StatsGroupings{}
	this.Groupings = groupings
	return &this
}

// NewStatsGroupingsWithDefaults instantiates a new StatsGroupings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsGroupingsWithDefaults() *StatsGroupings {
	this := StatsGroupings{}
	return &this
}

// GetGroupings returns the Groupings field value
func (o *StatsGroupings) GetGroupings() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Groupings
}

// GetGroupingsOk returns a tuple with the Groupings field value
// and a boolean to check if the value has been set.
func (o *StatsGroupings) GetGroupingsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Groupings, true
}

// SetGroupings sets field value
func (o *StatsGroupings) SetGroupings(v map[string]string) {
	o.Groupings = v
}

func (o StatsGroupings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsGroupings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Groupings"] = o.Groupings

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatsGroupings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Groupings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsGroupings := _StatsGroupings{}

	err = json.Unmarshal(data, &varStatsGroupings)

	if err != nil {
		return err
	}

	*o = StatsGroupings(varStatsGroupings)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Groupings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatsGroupings struct {
	value *StatsGroupings
	isSet bool
}

func (v NullableStatsGroupings) Get() *StatsGroupings {
	return v.value
}

func (v *NullableStatsGroupings) Set(val *StatsGroupings) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsGroupings) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsGroupings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsGroupings(val *StatsGroupings) *NullableStatsGroupings {
	return &NullableStatsGroupings{value: val, isSet: true}
}

func (v NullableStatsGroupings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsGroupings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


