/*
Customa

E-Commerce BI & CRM Tool

API version: 3.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customa

import (
	"encoding/json"
	"time"
)

// checks if the Receipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receipt{}

// Receipt struct for Receipt
type Receipt struct {
	// Creation Timestamp of the item. Set internally by Customa, any given value is ignored.
	CreationDate *time.Time `json:"CreationDate,omitempty"`
	// Timestamp of the last change of the item in the database. Set internally by Customa, any given value is ignored.
	ModificationDate *time.Time `json:"ModificationDate,omitempty"`
	// ID of the receipt. Set internally by Customa, any given value is ignored.
	ID *string `json:"ID,omitempty"`
	// Type of the receipt.
	Type *string `json:"Type,omitempty"`
	// Receipt number
	Number *string `json:"Number,omitempty"`
	// ID of the customer.
	CustomerID *string `json:"CustomerID,omitempty"`
	ExternalOrderType *string `json:"ExternalOrderType,omitempty"`
	ExternalOrderID NullableInt32 `json:"ExternalOrderID,omitempty"`
	ExternalOrderExternalID NullableString `json:"ExternalOrderExternalID,omitempty"`
	ExternalOrderAccountID *int32 `json:"ExternalOrderAccountID,omitempty"`
	ExternalOrderSubAccountID *string `json:"ExternalOrderSubAccountID,omitempty"`
	// Marketplace of the receipt.
	Marketplace *string `json:"Marketplace,omitempty"`
	// Purchase date of the receipt.
	PurchaseDate *time.Time `json:"PurchaseDate,omitempty"`
	// Delivery date of the receipt. Will be removed in Q1 2026. Please use ReceiptDate instead.
	// Deprecated
	DeliveryDate NullableTime `json:"DeliveryDate,omitempty"`
	// Date of the receipt.
	ReceiptDate NullableTime `json:"ReceiptDate,omitempty"`
	// Referrer (last cookie) of the customer when creating this receipt.
	Referrer NullableString `json:"Referrer,omitempty"`
	// Referrer Channel of the customer when creating this receipt.
	ReferrerChannel NullableString `json:"ReferrerChannel,omitempty"`
	// Payment method of the receipt.
	PaymentMethod *string `json:"PaymentMethod,omitempty"`
	RevenueNet *Price `json:"RevenueNet,omitempty"`
	RevenueGross *Price `json:"RevenueGross,omitempty"`
	// Status of the receipt.
	ReceiptStatus *string `json:"ReceiptStatus,omitempty"`
	// Payment status of the receipt.
	PaymentStatus *string `json:"PaymentStatus,omitempty"`
	// Delivery status of the receipt.
	DeliveryStatus *string `json:"DeliveryStatus,omitempty"`
	// Google Click ID of this receipt.
	GoogleClickID NullableString `json:"GoogleClickID,omitempty"`
	// List of items in the receipt.
	Items []StrictReceiptItem `json:"Items,omitempty"`
	// Additional field data for the receipt.
	AdditionalFields []AdditionalField `json:"AdditionalFields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Receipt Receipt

// NewReceipt instantiates a new Receipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceipt() *Receipt {
	this := Receipt{}
	return &this
}

// NewReceiptWithDefaults instantiates a new Receipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptWithDefaults() *Receipt {
	this := Receipt{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *Receipt) GetCreationDate() time.Time {
	if o == nil || IsNil(o.CreationDate) {
		var ret time.Time
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *Receipt) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given time.Time and assigns it to the CreationDate field.
func (o *Receipt) SetCreationDate(v time.Time) {
	o.CreationDate = &v
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise.
func (o *Receipt) GetModificationDate() time.Time {
	if o == nil || IsNil(o.ModificationDate) {
		var ret time.Time
		return ret
	}
	return *o.ModificationDate
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetModificationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModificationDate) {
		return nil, false
	}
	return o.ModificationDate, true
}

// HasModificationDate returns a boolean if a field has been set.
func (o *Receipt) HasModificationDate() bool {
	if o != nil && !IsNil(o.ModificationDate) {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given time.Time and assigns it to the ModificationDate field.
func (o *Receipt) SetModificationDate(v time.Time) {
	o.ModificationDate = &v
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *Receipt) GetID() string {
	if o == nil || IsNil(o.ID) {
		var ret string
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetIDOk() (*string, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *Receipt) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given string and assigns it to the ID field.
func (o *Receipt) SetID(v string) {
	o.ID = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Receipt) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Receipt) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Receipt) SetType(v string) {
	o.Type = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *Receipt) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *Receipt) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *Receipt) SetNumber(v string) {
	o.Number = &v
}

// GetCustomerID returns the CustomerID field value if set, zero value otherwise.
func (o *Receipt) GetCustomerID() string {
	if o == nil || IsNil(o.CustomerID) {
		var ret string
		return ret
	}
	return *o.CustomerID
}

// GetCustomerIDOk returns a tuple with the CustomerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetCustomerIDOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerID) {
		return nil, false
	}
	return o.CustomerID, true
}

// HasCustomerID returns a boolean if a field has been set.
func (o *Receipt) HasCustomerID() bool {
	if o != nil && !IsNil(o.CustomerID) {
		return true
	}

	return false
}

// SetCustomerID gets a reference to the given string and assigns it to the CustomerID field.
func (o *Receipt) SetCustomerID(v string) {
	o.CustomerID = &v
}

// GetExternalOrderType returns the ExternalOrderType field value if set, zero value otherwise.
func (o *Receipt) GetExternalOrderType() string {
	if o == nil || IsNil(o.ExternalOrderType) {
		var ret string
		return ret
	}
	return *o.ExternalOrderType
}

// GetExternalOrderTypeOk returns a tuple with the ExternalOrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetExternalOrderTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalOrderType) {
		return nil, false
	}
	return o.ExternalOrderType, true
}

// HasExternalOrderType returns a boolean if a field has been set.
func (o *Receipt) HasExternalOrderType() bool {
	if o != nil && !IsNil(o.ExternalOrderType) {
		return true
	}

	return false
}

// SetExternalOrderType gets a reference to the given string and assigns it to the ExternalOrderType field.
func (o *Receipt) SetExternalOrderType(v string) {
	o.ExternalOrderType = &v
}

// GetExternalOrderID returns the ExternalOrderID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetExternalOrderID() int32 {
	if o == nil || IsNil(o.ExternalOrderID.Get()) {
		var ret int32
		return ret
	}
	return *o.ExternalOrderID.Get()
}

// GetExternalOrderIDOk returns a tuple with the ExternalOrderID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetExternalOrderIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderID.Get(), o.ExternalOrderID.IsSet()
}

// HasExternalOrderID returns a boolean if a field has been set.
func (o *Receipt) HasExternalOrderID() bool {
	if o != nil && o.ExternalOrderID.IsSet() {
		return true
	}

	return false
}

// SetExternalOrderID gets a reference to the given NullableInt32 and assigns it to the ExternalOrderID field.
func (o *Receipt) SetExternalOrderID(v int32) {
	o.ExternalOrderID.Set(&v)
}
// SetExternalOrderIDNil sets the value for ExternalOrderID to be an explicit nil
func (o *Receipt) SetExternalOrderIDNil() {
	o.ExternalOrderID.Set(nil)
}

// UnsetExternalOrderID ensures that no value is present for ExternalOrderID, not even an explicit nil
func (o *Receipt) UnsetExternalOrderID() {
	o.ExternalOrderID.Unset()
}

// GetExternalOrderExternalID returns the ExternalOrderExternalID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetExternalOrderExternalID() string {
	if o == nil || IsNil(o.ExternalOrderExternalID.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalOrderExternalID.Get()
}

// GetExternalOrderExternalIDOk returns a tuple with the ExternalOrderExternalID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetExternalOrderExternalIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalOrderExternalID.Get(), o.ExternalOrderExternalID.IsSet()
}

// HasExternalOrderExternalID returns a boolean if a field has been set.
func (o *Receipt) HasExternalOrderExternalID() bool {
	if o != nil && o.ExternalOrderExternalID.IsSet() {
		return true
	}

	return false
}

// SetExternalOrderExternalID gets a reference to the given NullableString and assigns it to the ExternalOrderExternalID field.
func (o *Receipt) SetExternalOrderExternalID(v string) {
	o.ExternalOrderExternalID.Set(&v)
}
// SetExternalOrderExternalIDNil sets the value for ExternalOrderExternalID to be an explicit nil
func (o *Receipt) SetExternalOrderExternalIDNil() {
	o.ExternalOrderExternalID.Set(nil)
}

// UnsetExternalOrderExternalID ensures that no value is present for ExternalOrderExternalID, not even an explicit nil
func (o *Receipt) UnsetExternalOrderExternalID() {
	o.ExternalOrderExternalID.Unset()
}

// GetExternalOrderAccountID returns the ExternalOrderAccountID field value if set, zero value otherwise.
func (o *Receipt) GetExternalOrderAccountID() int32 {
	if o == nil || IsNil(o.ExternalOrderAccountID) {
		var ret int32
		return ret
	}
	return *o.ExternalOrderAccountID
}

// GetExternalOrderAccountIDOk returns a tuple with the ExternalOrderAccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetExternalOrderAccountIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ExternalOrderAccountID) {
		return nil, false
	}
	return o.ExternalOrderAccountID, true
}

// HasExternalOrderAccountID returns a boolean if a field has been set.
func (o *Receipt) HasExternalOrderAccountID() bool {
	if o != nil && !IsNil(o.ExternalOrderAccountID) {
		return true
	}

	return false
}

// SetExternalOrderAccountID gets a reference to the given int32 and assigns it to the ExternalOrderAccountID field.
func (o *Receipt) SetExternalOrderAccountID(v int32) {
	o.ExternalOrderAccountID = &v
}

// GetExternalOrderSubAccountID returns the ExternalOrderSubAccountID field value if set, zero value otherwise.
func (o *Receipt) GetExternalOrderSubAccountID() string {
	if o == nil || IsNil(o.ExternalOrderSubAccountID) {
		var ret string
		return ret
	}
	return *o.ExternalOrderSubAccountID
}

// GetExternalOrderSubAccountIDOk returns a tuple with the ExternalOrderSubAccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetExternalOrderSubAccountIDOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalOrderSubAccountID) {
		return nil, false
	}
	return o.ExternalOrderSubAccountID, true
}

// HasExternalOrderSubAccountID returns a boolean if a field has been set.
func (o *Receipt) HasExternalOrderSubAccountID() bool {
	if o != nil && !IsNil(o.ExternalOrderSubAccountID) {
		return true
	}

	return false
}

// SetExternalOrderSubAccountID gets a reference to the given string and assigns it to the ExternalOrderSubAccountID field.
func (o *Receipt) SetExternalOrderSubAccountID(v string) {
	o.ExternalOrderSubAccountID = &v
}

// GetMarketplace returns the Marketplace field value if set, zero value otherwise.
func (o *Receipt) GetMarketplace() string {
	if o == nil || IsNil(o.Marketplace) {
		var ret string
		return ret
	}
	return *o.Marketplace
}

// GetMarketplaceOk returns a tuple with the Marketplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetMarketplaceOk() (*string, bool) {
	if o == nil || IsNil(o.Marketplace) {
		return nil, false
	}
	return o.Marketplace, true
}

// HasMarketplace returns a boolean if a field has been set.
func (o *Receipt) HasMarketplace() bool {
	if o != nil && !IsNil(o.Marketplace) {
		return true
	}

	return false
}

// SetMarketplace gets a reference to the given string and assigns it to the Marketplace field.
func (o *Receipt) SetMarketplace(v string) {
	o.Marketplace = &v
}

// GetPurchaseDate returns the PurchaseDate field value if set, zero value otherwise.
func (o *Receipt) GetPurchaseDate() time.Time {
	if o == nil || IsNil(o.PurchaseDate) {
		var ret time.Time
		return ret
	}
	return *o.PurchaseDate
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetPurchaseDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PurchaseDate) {
		return nil, false
	}
	return o.PurchaseDate, true
}

// HasPurchaseDate returns a boolean if a field has been set.
func (o *Receipt) HasPurchaseDate() bool {
	if o != nil && !IsNil(o.PurchaseDate) {
		return true
	}

	return false
}

// SetPurchaseDate gets a reference to the given time.Time and assigns it to the PurchaseDate field.
func (o *Receipt) SetPurchaseDate(v time.Time) {
	o.PurchaseDate = &v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *Receipt) GetDeliveryDate() time.Time {
	if o == nil || IsNil(o.DeliveryDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeliveryDate.Get()
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *Receipt) GetDeliveryDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeliveryDate.Get(), o.DeliveryDate.IsSet()
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *Receipt) HasDeliveryDate() bool {
	if o != nil && o.DeliveryDate.IsSet() {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given NullableTime and assigns it to the DeliveryDate field.
// Deprecated
func (o *Receipt) SetDeliveryDate(v time.Time) {
	o.DeliveryDate.Set(&v)
}
// SetDeliveryDateNil sets the value for DeliveryDate to be an explicit nil
func (o *Receipt) SetDeliveryDateNil() {
	o.DeliveryDate.Set(nil)
}

// UnsetDeliveryDate ensures that no value is present for DeliveryDate, not even an explicit nil
func (o *Receipt) UnsetDeliveryDate() {
	o.DeliveryDate.Unset()
}

// GetReceiptDate returns the ReceiptDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetReceiptDate() time.Time {
	if o == nil || IsNil(o.ReceiptDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReceiptDate.Get()
}

// GetReceiptDateOk returns a tuple with the ReceiptDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetReceiptDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceiptDate.Get(), o.ReceiptDate.IsSet()
}

// HasReceiptDate returns a boolean if a field has been set.
func (o *Receipt) HasReceiptDate() bool {
	if o != nil && o.ReceiptDate.IsSet() {
		return true
	}

	return false
}

// SetReceiptDate gets a reference to the given NullableTime and assigns it to the ReceiptDate field.
func (o *Receipt) SetReceiptDate(v time.Time) {
	o.ReceiptDate.Set(&v)
}
// SetReceiptDateNil sets the value for ReceiptDate to be an explicit nil
func (o *Receipt) SetReceiptDateNil() {
	o.ReceiptDate.Set(nil)
}

// UnsetReceiptDate ensures that no value is present for ReceiptDate, not even an explicit nil
func (o *Receipt) UnsetReceiptDate() {
	o.ReceiptDate.Unset()
}

// GetReferrer returns the Referrer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetReferrer() string {
	if o == nil || IsNil(o.Referrer.Get()) {
		var ret string
		return ret
	}
	return *o.Referrer.Get()
}

// GetReferrerOk returns a tuple with the Referrer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetReferrerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Referrer.Get(), o.Referrer.IsSet()
}

// HasReferrer returns a boolean if a field has been set.
func (o *Receipt) HasReferrer() bool {
	if o != nil && o.Referrer.IsSet() {
		return true
	}

	return false
}

// SetReferrer gets a reference to the given NullableString and assigns it to the Referrer field.
func (o *Receipt) SetReferrer(v string) {
	o.Referrer.Set(&v)
}
// SetReferrerNil sets the value for Referrer to be an explicit nil
func (o *Receipt) SetReferrerNil() {
	o.Referrer.Set(nil)
}

// UnsetReferrer ensures that no value is present for Referrer, not even an explicit nil
func (o *Receipt) UnsetReferrer() {
	o.Referrer.Unset()
}

// GetReferrerChannel returns the ReferrerChannel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetReferrerChannel() string {
	if o == nil || IsNil(o.ReferrerChannel.Get()) {
		var ret string
		return ret
	}
	return *o.ReferrerChannel.Get()
}

// GetReferrerChannelOk returns a tuple with the ReferrerChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetReferrerChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferrerChannel.Get(), o.ReferrerChannel.IsSet()
}

// HasReferrerChannel returns a boolean if a field has been set.
func (o *Receipt) HasReferrerChannel() bool {
	if o != nil && o.ReferrerChannel.IsSet() {
		return true
	}

	return false
}

// SetReferrerChannel gets a reference to the given NullableString and assigns it to the ReferrerChannel field.
func (o *Receipt) SetReferrerChannel(v string) {
	o.ReferrerChannel.Set(&v)
}
// SetReferrerChannelNil sets the value for ReferrerChannel to be an explicit nil
func (o *Receipt) SetReferrerChannelNil() {
	o.ReferrerChannel.Set(nil)
}

// UnsetReferrerChannel ensures that no value is present for ReferrerChannel, not even an explicit nil
func (o *Receipt) UnsetReferrerChannel() {
	o.ReferrerChannel.Unset()
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *Receipt) GetPaymentMethod() string {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret string
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetPaymentMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *Receipt) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given string and assigns it to the PaymentMethod field.
func (o *Receipt) SetPaymentMethod(v string) {
	o.PaymentMethod = &v
}

// GetRevenueNet returns the RevenueNet field value if set, zero value otherwise.
func (o *Receipt) GetRevenueNet() Price {
	if o == nil || IsNil(o.RevenueNet) {
		var ret Price
		return ret
	}
	return *o.RevenueNet
}

// GetRevenueNetOk returns a tuple with the RevenueNet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetRevenueNetOk() (*Price, bool) {
	if o == nil || IsNil(o.RevenueNet) {
		return nil, false
	}
	return o.RevenueNet, true
}

// HasRevenueNet returns a boolean if a field has been set.
func (o *Receipt) HasRevenueNet() bool {
	if o != nil && !IsNil(o.RevenueNet) {
		return true
	}

	return false
}

// SetRevenueNet gets a reference to the given Price and assigns it to the RevenueNet field.
func (o *Receipt) SetRevenueNet(v Price) {
	o.RevenueNet = &v
}

// GetRevenueGross returns the RevenueGross field value if set, zero value otherwise.
func (o *Receipt) GetRevenueGross() Price {
	if o == nil || IsNil(o.RevenueGross) {
		var ret Price
		return ret
	}
	return *o.RevenueGross
}

// GetRevenueGrossOk returns a tuple with the RevenueGross field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetRevenueGrossOk() (*Price, bool) {
	if o == nil || IsNil(o.RevenueGross) {
		return nil, false
	}
	return o.RevenueGross, true
}

// HasRevenueGross returns a boolean if a field has been set.
func (o *Receipt) HasRevenueGross() bool {
	if o != nil && !IsNil(o.RevenueGross) {
		return true
	}

	return false
}

// SetRevenueGross gets a reference to the given Price and assigns it to the RevenueGross field.
func (o *Receipt) SetRevenueGross(v Price) {
	o.RevenueGross = &v
}

// GetReceiptStatus returns the ReceiptStatus field value if set, zero value otherwise.
func (o *Receipt) GetReceiptStatus() string {
	if o == nil || IsNil(o.ReceiptStatus) {
		var ret string
		return ret
	}
	return *o.ReceiptStatus
}

// GetReceiptStatusOk returns a tuple with the ReceiptStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetReceiptStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiptStatus) {
		return nil, false
	}
	return o.ReceiptStatus, true
}

// HasReceiptStatus returns a boolean if a field has been set.
func (o *Receipt) HasReceiptStatus() bool {
	if o != nil && !IsNil(o.ReceiptStatus) {
		return true
	}

	return false
}

// SetReceiptStatus gets a reference to the given string and assigns it to the ReceiptStatus field.
func (o *Receipt) SetReceiptStatus(v string) {
	o.ReceiptStatus = &v
}

// GetPaymentStatus returns the PaymentStatus field value if set, zero value otherwise.
func (o *Receipt) GetPaymentStatus() string {
	if o == nil || IsNil(o.PaymentStatus) {
		var ret string
		return ret
	}
	return *o.PaymentStatus
}

// GetPaymentStatusOk returns a tuple with the PaymentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetPaymentStatusOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentStatus) {
		return nil, false
	}
	return o.PaymentStatus, true
}

// HasPaymentStatus returns a boolean if a field has been set.
func (o *Receipt) HasPaymentStatus() bool {
	if o != nil && !IsNil(o.PaymentStatus) {
		return true
	}

	return false
}

// SetPaymentStatus gets a reference to the given string and assigns it to the PaymentStatus field.
func (o *Receipt) SetPaymentStatus(v string) {
	o.PaymentStatus = &v
}

// GetDeliveryStatus returns the DeliveryStatus field value if set, zero value otherwise.
func (o *Receipt) GetDeliveryStatus() string {
	if o == nil || IsNil(o.DeliveryStatus) {
		var ret string
		return ret
	}
	return *o.DeliveryStatus
}

// GetDeliveryStatusOk returns a tuple with the DeliveryStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetDeliveryStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveryStatus) {
		return nil, false
	}
	return o.DeliveryStatus, true
}

// HasDeliveryStatus returns a boolean if a field has been set.
func (o *Receipt) HasDeliveryStatus() bool {
	if o != nil && !IsNil(o.DeliveryStatus) {
		return true
	}

	return false
}

// SetDeliveryStatus gets a reference to the given string and assigns it to the DeliveryStatus field.
func (o *Receipt) SetDeliveryStatus(v string) {
	o.DeliveryStatus = &v
}

// GetGoogleClickID returns the GoogleClickID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Receipt) GetGoogleClickID() string {
	if o == nil || IsNil(o.GoogleClickID.Get()) {
		var ret string
		return ret
	}
	return *o.GoogleClickID.Get()
}

// GetGoogleClickIDOk returns a tuple with the GoogleClickID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetGoogleClickIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GoogleClickID.Get(), o.GoogleClickID.IsSet()
}

// HasGoogleClickID returns a boolean if a field has been set.
func (o *Receipt) HasGoogleClickID() bool {
	if o != nil && o.GoogleClickID.IsSet() {
		return true
	}

	return false
}

// SetGoogleClickID gets a reference to the given NullableString and assigns it to the GoogleClickID field.
func (o *Receipt) SetGoogleClickID(v string) {
	o.GoogleClickID.Set(&v)
}
// SetGoogleClickIDNil sets the value for GoogleClickID to be an explicit nil
func (o *Receipt) SetGoogleClickIDNil() {
	o.GoogleClickID.Set(nil)
}

// UnsetGoogleClickID ensures that no value is present for GoogleClickID, not even an explicit nil
func (o *Receipt) UnsetGoogleClickID() {
	o.GoogleClickID.Unset()
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *Receipt) GetItems() []StrictReceiptItem {
	if o == nil || IsNil(o.Items) {
		var ret []StrictReceiptItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetItemsOk() ([]StrictReceiptItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *Receipt) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []StrictReceiptItem and assigns it to the Items field.
func (o *Receipt) SetItems(v []StrictReceiptItem) {
	o.Items = v
}

// GetAdditionalFields returns the AdditionalFields field value if set, zero value otherwise.
func (o *Receipt) GetAdditionalFields() []AdditionalField {
	if o == nil || IsNil(o.AdditionalFields) {
		var ret []AdditionalField
		return ret
	}
	return o.AdditionalFields
}

// GetAdditionalFieldsOk returns a tuple with the AdditionalFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetAdditionalFieldsOk() ([]AdditionalField, bool) {
	if o == nil || IsNil(o.AdditionalFields) {
		return nil, false
	}
	return o.AdditionalFields, true
}

// HasAdditionalFields returns a boolean if a field has been set.
func (o *Receipt) HasAdditionalFields() bool {
	if o != nil && !IsNil(o.AdditionalFields) {
		return true
	}

	return false
}

// SetAdditionalFields gets a reference to the given []AdditionalField and assigns it to the AdditionalFields field.
func (o *Receipt) SetAdditionalFields(v []AdditionalField) {
	o.AdditionalFields = v
}

func (o Receipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.ModificationDate) {
		toSerialize["ModificationDate"] = o.ModificationDate
	}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.Number) {
		toSerialize["Number"] = o.Number
	}
	if !IsNil(o.CustomerID) {
		toSerialize["CustomerID"] = o.CustomerID
	}
	if !IsNil(o.ExternalOrderType) {
		toSerialize["ExternalOrderType"] = o.ExternalOrderType
	}
	if o.ExternalOrderID.IsSet() {
		toSerialize["ExternalOrderID"] = o.ExternalOrderID.Get()
	}
	if o.ExternalOrderExternalID.IsSet() {
		toSerialize["ExternalOrderExternalID"] = o.ExternalOrderExternalID.Get()
	}
	if !IsNil(o.ExternalOrderAccountID) {
		toSerialize["ExternalOrderAccountID"] = o.ExternalOrderAccountID
	}
	if !IsNil(o.ExternalOrderSubAccountID) {
		toSerialize["ExternalOrderSubAccountID"] = o.ExternalOrderSubAccountID
	}
	if !IsNil(o.Marketplace) {
		toSerialize["Marketplace"] = o.Marketplace
	}
	if !IsNil(o.PurchaseDate) {
		toSerialize["PurchaseDate"] = o.PurchaseDate
	}
	if o.DeliveryDate.IsSet() {
		toSerialize["DeliveryDate"] = o.DeliveryDate.Get()
	}
	if o.ReceiptDate.IsSet() {
		toSerialize["ReceiptDate"] = o.ReceiptDate.Get()
	}
	if o.Referrer.IsSet() {
		toSerialize["Referrer"] = o.Referrer.Get()
	}
	if o.ReferrerChannel.IsSet() {
		toSerialize["ReferrerChannel"] = o.ReferrerChannel.Get()
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["PaymentMethod"] = o.PaymentMethod
	}
	if !IsNil(o.RevenueNet) {
		toSerialize["RevenueNet"] = o.RevenueNet
	}
	if !IsNil(o.RevenueGross) {
		toSerialize["RevenueGross"] = o.RevenueGross
	}
	if !IsNil(o.ReceiptStatus) {
		toSerialize["ReceiptStatus"] = o.ReceiptStatus
	}
	if !IsNil(o.PaymentStatus) {
		toSerialize["PaymentStatus"] = o.PaymentStatus
	}
	if !IsNil(o.DeliveryStatus) {
		toSerialize["DeliveryStatus"] = o.DeliveryStatus
	}
	if o.GoogleClickID.IsSet() {
		toSerialize["GoogleClickID"] = o.GoogleClickID.Get()
	}
	if !IsNil(o.Items) {
		toSerialize["Items"] = o.Items
	}
	if !IsNil(o.AdditionalFields) {
		toSerialize["AdditionalFields"] = o.AdditionalFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Receipt) UnmarshalJSON(data []byte) (err error) {
	varReceipt := _Receipt{}

	err = json.Unmarshal(data, &varReceipt)

	if err != nil {
		return err
	}

	*o = Receipt(varReceipt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "CreationDate")
		delete(additionalProperties, "ModificationDate")
		delete(additionalProperties, "ID")
		delete(additionalProperties, "Type")
		delete(additionalProperties, "Number")
		delete(additionalProperties, "CustomerID")
		delete(additionalProperties, "ExternalOrderType")
		delete(additionalProperties, "ExternalOrderID")
		delete(additionalProperties, "ExternalOrderExternalID")
		delete(additionalProperties, "ExternalOrderAccountID")
		delete(additionalProperties, "ExternalOrderSubAccountID")
		delete(additionalProperties, "Marketplace")
		delete(additionalProperties, "PurchaseDate")
		delete(additionalProperties, "DeliveryDate")
		delete(additionalProperties, "ReceiptDate")
		delete(additionalProperties, "Referrer")
		delete(additionalProperties, "ReferrerChannel")
		delete(additionalProperties, "PaymentMethod")
		delete(additionalProperties, "RevenueNet")
		delete(additionalProperties, "RevenueGross")
		delete(additionalProperties, "ReceiptStatus")
		delete(additionalProperties, "PaymentStatus")
		delete(additionalProperties, "DeliveryStatus")
		delete(additionalProperties, "GoogleClickID")
		delete(additionalProperties, "Items")
		delete(additionalProperties, "AdditionalFields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReceipt struct {
	value *Receipt
	isSet bool
}

func (v NullableReceipt) Get() *Receipt {
	return v.value
}

func (v *NullableReceipt) Set(val *Receipt) {
	v.value = val
	v.isSet = true
}

func (v NullableReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceipt(val *Receipt) *NullableReceipt {
	return &NullableReceipt{value: val, isSet: true}
}

func (v NullableReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


